#pragma once

#include "Engine/Core/Base.h"
#include "Engine/Core/UUID.h"
#include "Engine/Reflection/FieldType.h"
#include "Engine/Reflection/Value.h"
#include "Engine/Reflection/VariantValue.h"

#include <glm/glm.hpp>
#include <glm/gtc/quaternion.hpp>

#include <cstddef>
#include <cstdint>
#include <map>
#include <memory>
#include <string>
#include <string_view>
#include <type_traits>
#include <utility>
#include <vector>

namespace Engine {

	class EnumInfo;
	class StructInfo;

	// A compile-time identity of a C++ type without RTTI (first-party code never uses typeid, §3): the address of a
	// per-type constant. Stable for the lifetime of the process and unique per type in one binary; never persisted
	// (registry names are the persistent identities, §5.1).
	using TypeKey = const void*;

	namespace Detail {

		template<typename T>
		struct TypeKeyTag
		{
			static constexpr char Tag = 0;
		};

		// A distinct key for "glm::vec3/vec4 used as a colour" (FieldBuilder::ColorField), which shares its C++ type with
		// Vec3/Vec4 but reflects as Color3/Color4.
		template<typename T>
		struct ColorOf
		{
		};

	}

	template<typename T>
	[[nodiscard]] constexpr TypeKey TypeKeyOf()
	{
		return &Detail::TypeKeyTag<std::remove_cvref_t<T>>::Tag;
	}

	// Customization point for FieldType::AssetRef. Reflection (layer 1) cannot include the Asset module (layer 2), so the
	// typed asset handle of Asset/TypedAssetHandle.h specializes this trait next to its own definition with:
	//     static constexpr bool IsAssetField = true;
	//     static constexpr std::string_view AssetTypeName = "<AssetType name>";   // FieldMeta::AssetFilter
	//     static UUID GetHandle(const T& value);
	//     static void SetHandle(T& value, UUID handle);
	template<typename T>
	struct AssetFieldTraits
	{
		static constexpr bool IsAssetField = false;
	};

	// An owned, type-erased object created by TypeOps::Create (a default-constructed instance of the reflected type).
	using ObjectDeleter = void (*)(void* object);
	using ObjectPtr = std::unique_ptr<void, ObjectDeleter>;

	// Visits one entry of a Map in key order: `context` is the caller's pointer, `value` the entry's value.
	using MapEntryVisitor = void (*)(void* context, const std::string& key, const void* value);

	// Type-erased operations on a value of one reflected C++ type, generated by Detail::MakeTypeOps<T>() at registration.
	// Every pointer is null for a schema-only type (one that describes JSON without a C++ object, such as a script field
	// schema, M13); otherwise the ones listed for the type's kind are set. Addresses passed in must point to an object of
	// exactly that C++ type (a programmer error otherwise). Not thread-safe for the same object; main thread for
	// components (§4.11).
	struct TypeOps
	{
		// Every kind.
		ObjectPtr (*Create)() = nullptr;                               // a new default-constructed object
		void (*Copy)(void* destination, const void* source) = nullptr; // copy assignment
		void (*Reset)(void* object) = nullptr;                         // assigns the default value T{}

		// Scalar kinds and Variant (IsScalarFieldType). Write requires a Value of the type's kind; enum values must name an
		// enumerator (the callers validate against the EnumInfo first).
		Value (*Read)(const void* object) = nullptr;
		void (*Write)(void* object, const Value& value) = nullptr;

		// Array and Map.
		size_t (*GetCount)(const void* container) = nullptr;
		void (*Clear)(void* container) = nullptr;

		// Array (std::vector<T>): Resize default-constructs new elements; element addresses are invalidated by Resize and
		// Clear.
		void (*Resize)(void* array, size_t count) = nullptr;
		void* (*GetElement)(void* array, size_t index) = nullptr;
		const void* (*GetConstElement)(const void* array, size_t index) = nullptr;

		// Map (std::map<std::string, T>): entries are visited in std::map (byte-wise) key order. FindOrInsert inserts a
		// default-constructed value when the key is absent. Erase returns whether the key existed.
		void (*VisitEntries)(const void* map, void* context, MapEntryVisitor visitor) = nullptr;
		void* (*FindOrInsert)(void* map, std::string_view key) = nullptr;
		const void* (*Find)(const void* map, std::string_view key) = nullptr;
		bool (*Erase)(void* map, std::string_view key) = nullptr;
	};

	// The description of a reflected value type (Architecture §5.4, "TypeInfo"): its kind, the element type of an Array or
	// Map, the EnumInfo of an Enum, the StructInfo of a Struct, the accepted asset type of an AssetRef, and its type-erased
	// operations. Fields of the same C++ type share one TypeInfo. The TypeRegistry owns the TypeInfos of registered C++
	// types (TypeRegistry::GetOrCreateType); a script field schema owns its schema-only TypeInfos. Immutable after
	// construction; thread-safe.
	class TypeInfo
	{
	public:
		struct Specification
		{
			FieldType Kind = FieldType::Bool;
			// FieldTypeToString(Kind) for scalars and containers; the registry name for enums and structs.
			std::string Name;
			const TypeInfo* Element = nullptr;  // Array and Map
			const EnumInfo* Enum = nullptr;     // Enum
			const StructInfo* Struct = nullptr; // Struct
			std::string AssetTypeName;          // AssetRef: the accepted AssetType name, empty = any
			TypeOps Ops;                        // all null for a schema-only type
			TypeKey Key = nullptr;              // null for a schema-only type
		};

		explicit TypeInfo(Specification specification)
			: m_Specification(std::move(specification))
		{
		}

		[[nodiscard]] FieldType GetKind() const { return m_Specification.Kind; }
		[[nodiscard]] const std::string& GetName() const { return m_Specification.Name; }
		[[nodiscard]] const TypeInfo* GetElement() const { return m_Specification.Element; }
		[[nodiscard]] const EnumInfo* GetEnum() const { return m_Specification.Enum; }
		[[nodiscard]] const StructInfo* GetStruct() const { return m_Specification.Struct; }
		[[nodiscard]] const std::string& GetAssetTypeName() const { return m_Specification.AssetTypeName; }
		[[nodiscard]] const TypeOps& GetOps() const { return m_Specification.Ops; }
		[[nodiscard]] TypeKey GetKey() const { return m_Specification.Key; }
		// False for a schema-only type, which describes JSON but has no C++ storage.
		[[nodiscard]] bool HasOps() const { return m_Specification.Ops.Create != nullptr; }
	private:
		Specification m_Specification;
	};

	namespace Detail {

		template<typename T>
		struct VectorTraits
		{
			static constexpr bool IsVector = false;
		};

		template<typename Element, typename Allocator>
		struct VectorTraits<std::vector<Element, Allocator>>
		{
			static constexpr bool IsVector = true;
			using ElementType = Element;
		};

		template<typename T>
		struct StringMapTraits
		{
			static constexpr bool IsStringMap = false;
		};

		template<typename Element, typename Compare, typename Allocator>
		struct StringMapTraits<std::map<std::string, Element, Compare, Allocator>>
		{
			static constexpr bool IsStringMap = true;
			using ElementType = Element;
		};

		// The FieldType a member of C++ type T reflects as (FieldBuilder::Field). Any class type not listed is a Struct,
		// which must be registered before it is used as a field type. bool vectors are rejected: std::vector<bool> has no
		// addressable elements.
		template<typename T>
		[[nodiscard]] consteval FieldType DeduceFieldType()
		{
			if constexpr (std::is_same_v<T, bool>)
				return FieldType::Bool;
			else if constexpr (std::is_same_v<T, int32_t>)
				return FieldType::Int32;
			else if constexpr (std::is_same_v<T, uint32_t>)
				return FieldType::UInt32;
			else if constexpr (std::is_same_v<T, float>)
				return FieldType::Float;
			else if constexpr (std::is_same_v<T, glm::vec2>)
				return FieldType::Vec2;
			else if constexpr (std::is_same_v<T, glm::vec3>)
				return FieldType::Vec3;
			else if constexpr (std::is_same_v<T, glm::vec4>)
				return FieldType::Vec4;
			else if constexpr (std::is_same_v<T, glm::quat>)
				return FieldType::Quat;
			else if constexpr (std::is_same_v<T, glm::bvec3>)
				return FieldType::Bool3;
			else if constexpr (std::is_same_v<T, std::string>)
				return FieldType::String;
			else if constexpr (std::is_same_v<T, UUID>)
				return FieldType::EntityRef;
			else if constexpr (std::is_same_v<T, VariantValue>)
				return FieldType::Variant;
			else if constexpr (AssetFieldTraits<T>::IsAssetField)
				return FieldType::AssetRef;
			else if constexpr (std::is_enum_v<T>)
				return FieldType::Enum;
			else if constexpr (VectorTraits<T>::IsVector)
			{
				static_assert(!std::is_same_v<typename VectorTraits<T>::ElementType, bool>, "std::vector<bool> cannot be reflected");
				return FieldType::Array;
			}
			else if constexpr (StringMapTraits<T>::IsStringMap)
				return FieldType::Map;
			else if constexpr (std::is_class_v<T> && std::is_default_constructible_v<T> && std::is_copy_assignable_v<T>)
				return FieldType::Struct;
			else
				static_assert(sizeof(T) == 0, "this C++ type has no reflected FieldType (see FieldType.h)");
		}

		template<typename T>
		[[nodiscard]] ObjectPtr CreateObject()
		{
			return ObjectPtr(CreateScope<T>().release(), [](void* object)
			{
				std::default_delete<T>()(static_cast<T*>(object));
			});
		}

		// The Value of a scalar or Variant object of C++ type T reflected as `Kind`.
		template<typename T, FieldType Kind>
		[[nodiscard]] Value ReadScalar(const void* object)
		{
			const T& value = *static_cast<const T*>(object);
			if constexpr (Kind == FieldType::Bool)
				return Value::FromBool(value);
			else if constexpr (Kind == FieldType::Int32)
				return Value::FromInt32(value);
			else if constexpr (Kind == FieldType::UInt32)
				return Value::FromUInt32(value);
			else if constexpr (Kind == FieldType::Float)
				return Value::FromFloat(value);
			else if constexpr (Kind == FieldType::Vec2)
				return Value::FromVec2(value);
			else if constexpr (Kind == FieldType::Vec3)
				return Value::FromVec3(value);
			else if constexpr (Kind == FieldType::Vec4)
				return Value::FromVec4(value);
			else if constexpr (Kind == FieldType::Quat)
				return Value::FromQuat(value);
			else if constexpr (Kind == FieldType::Color3)
				return Value::FromColor3(value);
			else if constexpr (Kind == FieldType::Color4)
				return Value::FromColor4(value);
			else if constexpr (Kind == FieldType::Bool3)
				return Value::FromBool3(value);
			else if constexpr (Kind == FieldType::String)
				return Value::FromString(value);
			else if constexpr (Kind == FieldType::EntityRef)
				return Value::FromEntityRef(value);
			else if constexpr (Kind == FieldType::AssetRef)
				return Value::FromAssetRef(AssetFieldTraits<T>::GetHandle(value));
			else if constexpr (Kind == FieldType::Enum)
				return Value::FromEnum(static_cast<int64_t>(std::to_underlying(value)));
			else if constexpr (Kind == FieldType::Variant)
				return Value::FromVariant(value);
			else
				static_assert(sizeof(T) == 0, "ReadScalar needs a scalar or Variant kind");
		}

		// Assigns `value` (of kind `Kind`) to a scalar or Variant object of C++ type T.
		template<typename T, FieldType Kind>
		void WriteScalar(void* object, const Value& value)
		{
			T& target = *static_cast<T*>(object);
			if constexpr (Kind == FieldType::Bool)
				target = value.AsBool();
			else if constexpr (Kind == FieldType::Int32)
				target = value.AsInt32();
			else if constexpr (Kind == FieldType::UInt32)
				target = value.AsUInt32();
			else if constexpr (Kind == FieldType::Float)
				target = value.AsFloat();
			else if constexpr (Kind == FieldType::Vec2)
				target = value.AsVec2();
			else if constexpr (Kind == FieldType::Vec3 || Kind == FieldType::Color3)
				target = value.AsVec3();
			else if constexpr (Kind == FieldType::Vec4 || Kind == FieldType::Color4)
				target = value.AsVec4();
			else if constexpr (Kind == FieldType::Quat)
				target = value.AsQuat();
			else if constexpr (Kind == FieldType::Bool3)
				target = value.AsBool3();
			else if constexpr (Kind == FieldType::String)
				target = value.AsString();
			else if constexpr (Kind == FieldType::EntityRef)
				target = value.AsUUID();
			else if constexpr (Kind == FieldType::AssetRef)
				AssetFieldTraits<T>::SetHandle(target, value.AsUUID());
			else if constexpr (Kind == FieldType::Enum)
				target = static_cast<T>(static_cast<std::underlying_type_t<T>>(value.AsEnum()));
			else if constexpr (Kind == FieldType::Variant)
				target = value.AsVariant();
			else
				static_assert(sizeof(T) == 0, "WriteScalar needs a scalar or Variant kind");
		}

		// The type-erased operations of C++ type T reflected as `Kind` (Kind differs from DeduceFieldType<T>() only for
		// colours).
		template<typename T, FieldType Kind = DeduceFieldType<T>()>
		[[nodiscard]] TypeOps MakeTypeOps()
		{
			TypeOps ops;
			ops.Create = &CreateObject<T>;
			ops.Copy = [](void* destination, const void* source)
			{
				*static_cast<T*>(destination) = *static_cast<const T*>(source);
			};
			ops.Reset = [](void* object)
			{
				*static_cast<T*>(object) = T{};
			};

			if constexpr (IsScalarFieldType(Kind))
			{
				ops.Read = &ReadScalar<T, Kind>;
				ops.Write = &WriteScalar<T, Kind>;
			}
			else if constexpr (Kind == FieldType::Array)
			{
				ops.GetCount = [](const void* container) -> size_t
				{
					return static_cast<const T*>(container)->size();
				};
				ops.Clear = [](void* container)
				{
					static_cast<T*>(container)->clear();
				};
				ops.Resize = [](void* array, size_t count)
				{
					static_cast<T*>(array)->resize(count);
				};
				ops.GetElement = [](void* array, size_t index) -> void*
				{
					return &(*static_cast<T*>(array))[index];
				};
				ops.GetConstElement = [](const void* array, size_t index) -> const void*
				{
					return &(*static_cast<const T*>(array))[index];
				};
			}
			else if constexpr (Kind == FieldType::Map)
			{
				ops.GetCount = [](const void* container) -> size_t
				{
					return static_cast<const T*>(container)->size();
				};
				ops.Clear = [](void* container)
				{
					static_cast<T*>(container)->clear();
				};
				ops.VisitEntries = [](const void* map, void* context, MapEntryVisitor visitor)
				{
					for (const auto& [key, value] : *static_cast<const T*>(map))
						visitor(context, key, &value);
				};
				ops.FindOrInsert = [](void* map, std::string_view key) -> void*
				{
					return &static_cast<T*>(map)->try_emplace(std::string(key)).first->second;
				};
				ops.Find = [](const void* map, std::string_view key) -> const void*
				{
					const T& entries = *static_cast<const T*>(map);
					const auto found = entries.find(std::string(key));
					return found == entries.end() ? nullptr : &found->second;
				};
				ops.Erase = [](void* map, std::string_view key) -> bool
				{
					return static_cast<T*>(map)->erase(std::string(key)) != 0;
				};
			}
			return ops;
		}

	}

}
