#include "TestsPCH.h"

#include "Engine/AssetPipeline/Importers/GltfImporter.h"

#include "Engine/Asset/AssetDiagnostic.h"
#include "Engine/Asset/DocumentData.h"
#include "Engine/Asset/MaterialData.h"
#include "Engine/Asset/MeshData.h"
#include "Engine/Asset/TextureData.h"
#include "Engine/Core/FileSystem.h"
#include "Engine/Core/Hash.h"
#include "Engine/Core/Json/JsonReader.h"
#include "Engine/Core/Json/JsonWriter.h"
#include "Engine/Reflection/ComponentInfo.h"
#include "Engine/Reflection/StructInfo.h"
#include "Engine/Reflection/TypeRegistry.h"
#include "Engine/Scene/Components/MeshRendererComponent.h"
#include "Engine/Scene/Components/TransformComponent.h"
#include "Engine/Scene/Prefab.h"
#include "Support/AssetTestFixture.h"
#include "Support/TestData.h"

#include <nlohmann/json.hpp>

#include <algorithm>
#include <bit>
#include <limits>

// The glTF fixtures are generated by Tests/Data/Generate/MakeGltfFixtures.py into Tests/Data/Assets/Gltf (Roadmap M6):
// Box.gltf (data-URI buffer), Box.glb (binary chunk with a buffer-view image), Textured.gltf with Textured.bin and
// Textures/Checker.png (external files), NormalMapped.gltf (with TANGENT) and NormalMappedNoTangents.gltf, AlphaModes.gltf,
// DataUri.gltf (buffer and image as data URIs), ParentEscape.gltf ("../Outside.bin"), AbsoluteUri.gltf
// ("/Models/Box.bin"), DriveLetterUri.gltf ("C:/Models/Box.bin"), HttpUri.gltf ("http://example.com/Box.bin"),
// EncodedParentEscape.gltf ("%2e%2e/Outside.bin"), EncodedBackslash.gltf ("..%5COutside.bin"), EncodedAbsolute.gltf
// ("%2FModels/Box.bin"), EncodedUri.gltf with "Encoded Data/Box.bin" (URI "Encoded%20Data/Box.bin"),
// TexCoord1Occlusion.gltf, VertexColors.gltf, DracoRequired.gltf (extensionsRequired KHR_draco_mesh_compression),
// StandaloneTexture.gltf with Textures/Shared.png, Hierarchy.gltf, PrimitiveModes.gltf, SkippedContent.gltf,
// Materials.gltf and NoNormalsNoUvs.gltf (the generator's docstring describes each).

static_assert(std::endian::native == std::endian::little, "the hand-built glTF buffers below are little-endian");

namespace Engine {

	namespace {

		// Every fixture that imports.
		constexpr std::array<std::string_view, 15> ImportableFixtures = { "Box.gltf", "Box.glb", "Textured.gltf", "NormalMapped.gltf",
			"NormalMappedNoTangents.gltf", "AlphaModes.gltf", "DataUri.gltf", "TexCoord1Occlusion.gltf", "VertexColors.gltf", "StandaloneTexture.gltf",
			"Hierarchy.gltf", "PrimitiveModes.gltf", "SkippedContent.gltf", "Materials.gltf", "NoNormalsNoUvs.gltf" };

		// Copies Tests/Data/Assets/Gltf into project://Assets/Models.
		void CopyGltfFixtures(Test::AssetTestFixture& fixture)
		{
			const Result<std::vector<std::string>> files = Test::ListTestDataFiles("Assets/Gltf", { ".gltf", ".glb", ".bin", ".png" });
			REQUIRE_MESSAGE(files.has_value(), files.error().ToString());
			REQUIRE_FALSE(files->empty());
			for (const std::string& file : *files)
			{
				Result<Buffer> bytes = FileSystem::ReadFile(Test::GetTestDataPath(file));
				REQUIRE(bytes.has_value());
				fixture.WriteProjectFile("Assets/Models/" + file.substr(std::string_view("Assets/Gltf/").size()), *bytes);
			}
		}

		Json MakeDefaultSettings()
		{
			Json settings = Json::object();
			settings["Scale"] = 1.0;
			settings["GenerateMissingTangents"] = true;
			settings["ImportMaterials"] = true;
			settings["MergeMeshes"] = false;
			return settings;
		}

		AssetMetadata MakeGltfMetadata(AssetHandle handle, std::vector<SubAssetEntry> previous = {})
		{
			AssetMetadata metadata;
			metadata.Handle = handle;
			metadata.Type = AssetType::Prefab;
			metadata.Importer = std::string(GltfImporter::Id);
			metadata.ImporterVersion = GltfImporter::Version;
			metadata.Settings = VariantValue(MakeDefaultSettings());
			metadata.SubAssets = std::move(previous);
			return metadata;
		}

		// MakeGltfMetadata with one setting changed.
		AssetMetadata MakeGltfMetadata(AssetHandle handle, std::string_view setting, const Json& value)
		{
			AssetMetadata metadata = MakeGltfMetadata(handle);
			Json settings = MakeDefaultSettings();
			settings[std::string(setting)] = value;
			metadata.Settings = VariantValue(std::move(settings));
			return metadata;
		}

		// One import with what its context recorded.
		struct GltfImportRun
		{
			Result<ImportResult> Imported{};
			std::vector<ImportDependencyRead> Reads{};
			std::vector<ImportAssetLookup> Lookups{};
		};

		GltfImportRun RunGltfImport(Test::AssetTestFixture& fixture, std::string_view relative, const AssetMetadata& metadata,
			std::span<const ImportAssetLookupEntry> assets = {})
		{
			const Buffer bytes = fixture.ReadProjectFile(relative);
			ImportContext context({
				.Vfs = &fixture.GetVfs(),
				.SourcePath = fixture.ProjectPath(relative),
				.SourceBytes = bytes,
				.Settings = metadata.Settings,
				.Registry = &fixture.GetRegistry(),
				.Assets = assets,
				.EnvironmentBaker = nullptr,
				.ScriptDiagnostics = nullptr,
			});
			GltfImportRun run;
			run.Imported = GltfImporter().Import(context, metadata);
			run.Reads = context.GetDependencyReads();
			run.Lookups = context.GetLookups();
			return run;
		}

		Result<ImportResult> ImportGltf(Test::AssetTestFixture& fixture, std::string_view relative, const AssetMetadata& metadata,
			std::span<const ImportAssetLookupEntry> assets = {})
		{
			return RunGltfImport(fixture, relative, metadata, assets).Imported;
		}

		std::vector<SubAssetEntry> ToSubAssets(const ImportResult& result)
		{
			std::vector<SubAssetEntry> subAssets;
			for (const ImportedArtifact& artifact : result.Artifacts)
			{
				if (!artifact.SubAssetKey.empty())
					subAssets.push_back({ .Key = artifact.SubAssetKey, .Handle = artifact.Handle, .Type = artifact.Type });
			}
			return subAssets;
		}

		std::vector<std::string> GetKeys(const ImportResult& result, AssetType type)
		{
			std::vector<std::string> keys;
			for (const ImportedArtifact& artifact : result.Artifacts)
			{
				if (artifact.Type == type)
					keys.push_back(artifact.SubAssetKey);
			}
			return keys;
		}

		const ImportedArtifact* FindArtifact(const ImportResult& result, AssetType type)
		{
			const auto found = std::ranges::find_if(result.Artifacts, [type](const ImportedArtifact& artifact)
			{
				return artifact.Type == type;
			});
			return found == result.Artifacts.end() ? nullptr : &*found;
		}

		const ImportedArtifact* FindArtifact(const ImportResult& result, std::string_view key)
		{
			const auto found = std::ranges::find_if(result.Artifacts, [key](const ImportedArtifact& artifact)
			{
				return artifact.SubAssetKey == key;
			});
			return found == result.Artifacts.end() ? nullptr : &*found;
		}

		std::vector<std::string> GetDiagnosticSubjects(const ImportResult& result, std::string_view code)
		{
			std::vector<std::string> subjects;
			for (const AssetDiagnostic& diagnostic : result.Diagnostics)
			{
				if (diagnostic.Code == code)
					subjects.push_back(diagnostic.Subject);
			}
			return subjects;
		}

		AssetRef<MeshData> LoadMesh(const ImportedArtifact* artifact)
		{
			REQUIRE(artifact != nullptr);
			Result<AssetRef<MeshData>> mesh = LoadCookedMesh(artifact->Cooked);
			REQUIRE_MESSAGE(mesh.has_value(), mesh.error().ToString());
			return *mesh;
		}

		AssetRef<MaterialData> LoadMaterial(const Test::AssetTestFixture& fixture, const ImportedArtifact* artifact)
		{
			REQUIRE(artifact != nullptr);
			Result<AssetRef<MaterialData>> material = LoadCookedMaterial(artifact->Cooked, fixture.GetRegistry());
			REQUIRE_MESSAGE(material.has_value(), material.error().ToString());
			return *material;
		}

		// The prefab document of an import (its main artifact).
		Json LoadPrefabDocument(const ImportResult& result)
		{
			REQUIRE_FALSE(result.Artifacts.empty());
			Result<AssetRef<PrefabData>> prefab = LoadCookedPrefab(result.Artifacts.front().Cooked);
			REQUIRE_MESSAGE(prefab.has_value(), prefab.error().ToString());
			return *(*prefab)->Document;
		}

		// The entity of `document` whose "Name" is `name`.
		Json FindEntity(const Json& document, std::string_view name)
		{
			const Json& entities = document["Entities"];
			for (const Json& entity : entities)
			{
				if (entity["Name"] == Json(std::string(name)))
					return entity;
			}
			FAIL("no entity named '" << std::string(name) << "'");
			return Json();
		}

		TransformComponent ReadTransform(const Test::AssetTestFixture& fixture, const Json& entity)
		{
			const ComponentInfo* info = fixture.GetRegistry().FindComponent<TransformComponent>();
			REQUIRE(info != nullptr);
			TransformComponent transform;
			const Status read = info->FromJson(&transform, JsonReader(entity["Components"]["Transform"]), ReadContext{});
			REQUIRE_MESSAGE(read.has_value(), read.error().ToString());
			return transform;
		}

		// The mesh an entity's MeshRenderer draws, or the null handle without one.
		AssetHandle ReadRendererMesh(const Test::AssetTestFixture& fixture, const Json& entity)
		{
			if (!entity["Components"].contains("MeshRenderer"))
				return AssetHandle();
			const ComponentInfo* info = fixture.GetRegistry().FindComponent<MeshRendererComponent>();
			REQUIRE(info != nullptr);
			MeshRendererComponent renderer;
			const Status read = info->FromJson(&renderer, JsonReader(entity["Components"]["MeshRenderer"]), ReadContext{});
			REQUIRE_MESSAGE(read.has_value(), read.error().ToString());
			return renderer.Mesh.GetHandle();
		}

		std::string EncodeBase64(std::span<const std::byte> bytes)
		{
			constexpr std::string_view Alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
			std::string text;
			for (size_t i = 0; i < bytes.size(); i += 3)
			{
				const size_t count = std::min<size_t>(3, bytes.size() - i);
				uint32_t group = 0;
				for (size_t k = 0; k < 3; ++k)
					group = (group << 8) | (k < count ? static_cast<uint32_t>(bytes[i + k]) : 0u);
				for (size_t k = 0; k < 4; ++k)
					text.push_back(k <= count ? Alphabet[(group >> (18 - 6 * k)) & 0x3Fu] : '=');
			}
			return text;
		}

		// A glTF document with one node drawing one triangle-list primitive: `positions` (FLOAT VEC3) and `indices` (UNSIGNED_SHORT)
		// in one base64 data-URI buffer, without normals or texture coordinates.
		Json MakeTriangleDocument(std::span<const glm::vec3> positions, std::span<const uint16_t> indices)
		{
			Buffer data(positions.size_bytes() + indices.size_bytes());
			std::memcpy(data.data(), positions.data(), positions.size_bytes());
			std::memcpy(data.data() + positions.size_bytes(), indices.data(), indices.size_bytes());
			while (data.size() % 4 != 0)
				data.push_back(std::byte{ 0 });

			Json position = { { "bufferView", 0 }, { "componentType", 5126 }, { "count", positions.size() }, { "type", "VEC3" } };
			Json index = { { "bufferView", 1 }, { "componentType", 5123 }, { "count", indices.size() }, { "type", "SCALAR" } };
			Json document = Json::object();
			document["asset"] = { { "version", "2.0" } };
			document["buffers"] = Json::array({ { { "byteLength", data.size() }, { "uri", "data:application/octet-stream;base64," + EncodeBase64(data) } } });
			document["bufferViews"] = Json::array({ { { "buffer", 0 }, { "byteLength", positions.size_bytes() }, { "byteOffset", 0 } },
				{ { "buffer", 0 }, { "byteLength", indices.size_bytes() }, { "byteOffset", positions.size_bytes() } } });
			document["accessors"] = Json::array({ position, index });
			Json primitive = { { "attributes", { { "POSITION", 0 } } }, { "indices", 1 } };
			document["meshes"] = Json::array({ { { "name", "Triangles" }, { "primitives", Json::array({ primitive }) } } });
			document["nodes"] = Json::array({ { { "mesh", 0 }, { "name", "Triangles" } } });
			document["scenes"] = Json::array({ { { "nodes", Json::array({ 0 }) } } });
			document["scene"] = 0;
			return document;
		}

		// A glTF document without meshes whose only buffer has the URI `uri` (and, when given, whose only image has
		// `imageUri`): enough for ListExternalUris.
		Json MakeUriDocument(std::string_view uri, std::string_view imageUri = {})
		{
			Json document = Json::object();
			document["asset"] = { { "version", "2.0" } };
			document["buffers"] = Json::array({ { { "byteLength", 4 }, { "uri", std::string(uri) } } });
			if (!imageUri.empty())
				document["images"] = Json::array({ { { "uri", std::string(imageUri) } } });
			return document;
		}

		Result<std::vector<std::string>> ListUrisOf(const Json& document)
		{
			const std::string text = document.dump();
			return GltfImporter::ListExternalUris(AsBytes(text));
		}

		// Writes `document` to project://Assets/Models/<name> and imports it with default settings.
		Result<ImportResult> ImportDocument(Test::AssetTestFixture& fixture, std::string_view name, const Json& document,
			AssetHandle handle = AssetHandle(0x0dd0000000000001ull))
		{
			const std::string relative = "Assets/Models/" + std::string(name);
			fixture.WriteProjectText(relative, document.dump());
			return ImportGltf(fixture, relative, MakeGltfMetadata(handle));
		}

		// Box.gltf as JSON, to derive invalid variants from.
		Json ReadBoxDocument(Test::AssetTestFixture& fixture)
		{
			const Buffer bytes = fixture.ReadProjectFile("Assets/Models/Box.gltf");
			Result<Json> document = JsonReader::Parse(AsStringView(bytes));
			REQUIRE(document.has_value());
			return std::move(*document);
		}

		void CheckImportFails(const Result<ImportResult>& imported, ErrorCode code, std::initializer_list<std::string_view> fragments)
		{
			REQUIRE_FALSE(imported.has_value());
			const std::string message = imported.error().ToString();
			CAPTURE(message);
			CHECK(imported.error().GetCode() == code);
			for (const std::string_view fragment : fragments)
			{
				CAPTURE(std::string(fragment));
				CHECK(message.find(fragment) != std::string::npos);
			}
		}

	}

	TEST_SUITE("AssetPipeline")
	{
		TEST_CASE("GltfImporter: every fixture imports")
		{
			Test::AssetTestFixture fixture;
			CopyGltfFixtures(fixture);
			for (const std::string_view name : ImportableFixtures)
			{
				CAPTURE(std::string(name));
				Result<ImportResult> imported = ImportGltf(fixture, "Assets/Models/" + std::string(name), MakeGltfMetadata(AssetHandle(0x9000 + name.size())));
				REQUIRE_MESSAGE(imported.has_value(), imported.error().ToString());
				// The main asset is the prefab, first; then at least one mesh sub-asset, keys sorted.
				REQUIRE_FALSE(imported->Artifacts.empty());
				CHECK(imported->Artifacts.front().Type == AssetType::Prefab);
				CHECK(imported->Artifacts.front().SubAssetKey.empty());
				const ImportedArtifact* mesh = FindArtifact(*imported, AssetType::Mesh);
				REQUIRE(mesh != nullptr);
				Result<AssetRef<MeshData>> loaded = LoadCookedMesh(mesh->Cooked);
				REQUIRE_MESSAGE(loaded.has_value(), loaded.error().ToString());
				CHECK(ValidateMeshData(**loaded).has_value());
				for (size_t index = 2; index < imported->Artifacts.size(); ++index)
					CHECK(imported->Artifacts[index - 1].SubAssetKey < imported->Artifacts[index].SubAssetKey);
				Result<AssetRef<PrefabData>> prefab = LoadCookedPrefab(imported->Artifacts.front().Cooked);
				CHECK(prefab.has_value());
			}

			// The material sub-assets carry the alpha modes (AlphaModes.gltf: OPAQUE, MASK with cutoff 0.25, BLEND).
			Result<ImportResult> alpha = ImportGltf(fixture, "Assets/Models/AlphaModes.gltf", MakeGltfMetadata(AssetHandle(0xa1)));
			REQUIRE(alpha.has_value());
			std::vector<AlphaMode> modes;
			std::vector<float> cutoffs;
			for (const ImportedArtifact& artifact : alpha->Artifacts)
			{
				if (artifact.Type != AssetType::Material)
					continue;
				Result<AssetRef<MaterialData>> material = LoadCookedMaterial(artifact.Cooked, fixture.GetRegistry());
				REQUIRE(material.has_value());
				modes.push_back((*material)->AlphaMode);
				cutoffs.push_back((*material)->AlphaCutoff);
			}
			CHECK(modes == std::vector<AlphaMode>{ AlphaMode::Opaque, AlphaMode::Mask, AlphaMode::Blend });
			REQUIRE(cutoffs.size() == 3);
			CHECK(cutoffs[1] == 0.25f);
		}

		TEST_CASE("GltfImporter: required Draco extension is rejected with a precise message")
		{
			Test::AssetTestFixture fixture;
			CopyGltfFixtures(fixture);
			Result<ImportResult> imported = ImportGltf(fixture, "Assets/Models/DracoRequired.gltf", MakeGltfMetadata(AssetHandle(0xd1)));
			REQUIRE_FALSE(imported.has_value());
			CHECK(imported.error().GetCode() == ErrorCode::ImportFailed);
			const std::string message = imported.error().ToString();
			CHECK(message.find("KHR_draco_mesh_compression") != std::string::npos);
			CHECK(message.find("Assets/Models/DracoRequired.gltf") != std::string::npos);
		}

		TEST_CASE("GltfImporter: other unsupported required extensions are rejected, supported ones import")
		{
			Test::AssetTestFixture fixture;
			for (const std::string_view extension : { "EXT_meshopt_compression", "KHR_texture_basisu", "KHR_materials_variants" })
			{
				CAPTURE(std::string(extension));
				Json document = Json::object();
				document["asset"] = { { "version", "2.0" } };
				document["extensionsUsed"] = Json::array({ std::string(extension) });
				document["extensionsRequired"] = Json::array({ std::string(extension) });
				CheckImportFails(ImportDocument(fixture, "Required.gltf", document), ErrorCode::ImportFailed, { extension, "Assets/Models/Required.gltf" });
			}

			// The three supported extensions may be required; a document without meshes gives a prefab with its root only.
			Json supported = Json::object();
			supported["asset"] = { { "version", "2.0" } };
			const Json extensions = Json::array({ "KHR_materials_emissive_strength", "KHR_texture_transform", "KHR_mesh_quantization" });
			supported["extensionsUsed"] = extensions;
			supported["extensionsRequired"] = extensions;
			Result<ImportResult> imported = ImportDocument(fixture, "Supported.gltf", supported);
			REQUIRE_MESSAGE(imported.has_value(), imported.error().ToString());
			REQUIRE(imported->Artifacts.size() == 1);
			const Json prefab = LoadPrefabDocument(*imported);
			REQUIRE(prefab["Entities"].size() == 1);
			CHECK(prefab["Entities"][0]["Name"] == Json("Supported"));
		}

		TEST_CASE("GltfImporter: reimport keeps sub-asset handles")
		{
			Test::AssetTestFixture fixture;
			CopyGltfFixtures(fixture);
			const AssetHandle source(0x7e7e000000000001ull);
			Result<ImportResult> first = ImportGltf(fixture, "Assets/Models/Textured.gltf", MakeGltfMetadata(source));
			REQUIRE_MESSAGE(first.has_value(), first.error().ToString());
			const std::vector<SubAssetEntry> subAssets = ToSubAssets(*first);
			REQUIRE_FALSE(subAssets.empty());
			for (const SubAssetEntry& entry : subAssets)
				CHECK(entry.Handle == DeriveSubAssetHandle(source, entry.Key));
			CHECK(GetKeys(*first, AssetType::Mesh) == std::vector<std::string>{ "mesh:0:TexturedCube" });
			CHECK(GetKeys(*first, AssetType::Material) == std::vector<std::string>{ "material:0:Checker", "material:1:Trim" });
			CHECK(GetKeys(*first, AssetType::Texture) == std::vector<std::string>{ "texture:0" });

			// A modified file (the node renamed, a second primitive's data unchanged): the keys, and so the handles, stay.
			Buffer modified = fixture.ReadProjectFile("Assets/Models/Textured.gltf");
			Result<Json> document = JsonReader::Parse(AsStringView(modified));
			REQUIRE(document.has_value());
			(*document)["nodes"][0]["name"] = "RenamedNode";
			fixture.WriteProjectText("Assets/Models/Textured.gltf", document->dump());
			Result<ImportResult> second = ImportGltf(fixture, "Assets/Models/Textured.gltf", MakeGltfMetadata(source, subAssets));
			REQUIRE_MESSAGE(second.has_value(), second.error().ToString());
			CHECK(ToSubAssets(*second) == subAssets);

			// The prefab's entity IDs are stable too: the node entity keeps Hash64(source, "node:0").
			const Json prefab = LoadPrefabDocument(*second);
			const Json node = FindEntity(prefab, "RenamedNode");
			CHECK(node["ID"] == Json(UUID(Hash64(source.GetValue(), "node:0")).ToString()));
		}

		TEST_CASE("GltfImporter: importing twice gives identical artifacts")
		{
			Test::AssetTestFixture fixture;
			CopyGltfFixtures(fixture);
			for (const std::string_view name : ImportableFixtures)
			{
				CAPTURE(std::string(name));
				const std::string relative = "Assets/Models/" + std::string(name);
				const AssetMetadata metadata = MakeGltfMetadata(AssetHandle(0x1234000000000000ull + name.size()));
				Result<ImportResult> first = ImportGltf(fixture, relative, metadata);
				Result<ImportResult> second = ImportGltf(fixture, relative, metadata);
				REQUIRE_MESSAGE(first.has_value(), first.error().ToString());
				REQUIRE_MESSAGE(second.has_value(), second.error().ToString());
				REQUIRE(first->Artifacts.size() == second->Artifacts.size());
				for (size_t index = 0; index < first->Artifacts.size(); ++index)
				{
					const ImportedArtifact& a = first->Artifacts[index];
					const ImportedArtifact& b = second->Artifacts[index];
					CHECK(a.Handle == b.Handle);
					CHECK(a.Type == b.Type);
					CHECK(a.SubAssetKey == b.SubAssetKey);
					CHECK(XXH64(a.Cooked) == XXH64(b.Cooked));
					CHECK(a.Cooked == b.Cooked);
				}
				CHECK(first->Dependencies == second->Dependencies);
				CHECK(first->Diagnostics == second->Diagnostics);
			}
		}

		TEST_CASE("GltfImporter: parent-escaping, absolute and http URIs are rejected")
		{
			Test::AssetTestFixture fixture;
			CopyGltfFixtures(fixture);
			struct Case
			{
				std::string_view File;
				std::string_view Uri;
			};
			const Case cases[] = {
				{ "ParentEscape.gltf", "../Outside.bin" },
				{ "AbsoluteUri.gltf", "/Models/Box.bin" },
				{ "DriveLetterUri.gltf", "C:/Models/Box.bin" },
				{ "HttpUri.gltf", "http://example.com/Box.bin" },
				// Percent-encoded escapes are validated after decoding, and named as written.
				{ "EncodedParentEscape.gltf", "%2e%2e/Outside.bin" },
				{ "EncodedBackslash.gltf", "..%5COutside.bin" },
				{ "EncodedAbsolute.gltf", "%2FModels/Box.bin" },
			};
			for (const Case& testCase : cases)
			{
				CAPTURE(std::string(testCase.File));
				GltfImportRun run = RunGltfImport(fixture, "Assets/Models/" + std::string(testCase.File), MakeGltfMetadata(AssetHandle(0xe1)));
				REQUIRE_FALSE(run.Imported.has_value());
				CHECK(run.Imported.error().GetCode() == ErrorCode::ImportFailed);
				CHECK(run.Imported.error().ToString().find(testCase.Uri) != std::string::npos);
				// Nothing outside the source's directory was read.
				CHECK(run.Reads.empty());
				// ListExternalUris (asset.import's closure) rejects them the same way.
				Result<std::vector<std::string>> uris = GltfImporter::ListExternalUris(fixture.ReadProjectFile("Assets/Models/" + std::string(testCase.File)));
				REQUIRE_FALSE(uris.has_value());
				CHECK(uris.error().GetCode() == ErrorCode::ImportFailed);
				CHECK(uris.error().ToString().find(testCase.Uri) != std::string::npos);
			}
		}

		TEST_CASE("GltfImporter: URIs are percent-decoded once, then validated")
		{
			// Accepted: decoded once, data URIs (in any case) never name a file, each path once, buffers before images.
			Result<std::vector<std::string>> slash = ListUrisOf(MakeUriDocument("Sub%2FDir/Data.bin", "Sub%20Dir/x%41.png"));
			REQUIRE_MESSAGE(slash.has_value(), slash.error().ToString());
			CHECK(*slash == std::vector<std::string>{ "Sub/Dir/Data.bin", "Sub Dir/xA.png" });
			Result<std::vector<std::string>> data = ListUrisOf(MakeUriDocument("DATA:application/octet-stream;base64,AAAAAA==", "Same.png"));
			REQUIRE_MESSAGE(data.has_value(), data.error().ToString());
			CHECK(*data == std::vector<std::string>{ "Same.png" });
			Result<std::vector<std::string>> twice = ListUrisOf(MakeUriDocument("Same.bin", "Same%2Ebin"));
			REQUIRE_MESSAGE(twice.has_value(), twice.error().ToString());
			CHECK(*twice == std::vector<std::string>{ "Same.bin" });
			Result<std::vector<std::string>> multibyte = ListUrisOf(MakeUriDocument("%C3%A9t%C3%A9.bin"));
			REQUIRE_MESSAGE(multibyte.has_value(), multibyte.error().ToString());
			CHECK(*multibyte == std::vector<std::string>{ "\xC3\xA9t\xC3\xA9.bin" });

			// Rejected, named as written: malformed escapes, NUL, invalid UTF-8, control characters, and every path that is
			// not a plain relative path once decoded.
			const std::string_view rejected[] = { "%zz.bin", "Data%4", "%00.bin", "%FF.bin", "Line%0ABreak.bin", "./Data.bin", "%2e/Data.bin",
				"Sub//Data.bin", "Sub/", "Sub/../Data.bin", "Sub/%2E%2E/Data.bin", "file:Data.bin", "Sub\\Data.bin", "//server/Data.bin", "" };
			for (const std::string_view uri : rejected)
			{
				CAPTURE(std::string(uri));
				Result<std::vector<std::string>> uris = ListUrisOf(MakeUriDocument(uri));
				REQUIRE_FALSE(uris.has_value());
				CHECK(uris.error().GetCode() == ErrorCode::ImportFailed);
				CHECK(uris.error().ToString().find("'" + std::string(uri) + "'") != std::string::npos);
				// An image URI follows the same rule.
				Result<std::vector<std::string>> images = ListUrisOf(MakeUriDocument("Good.bin", uri.empty() ? std::string_view("%00") : uri));
				CHECK_FALSE(images.has_value());
			}

			// The rule applies to the URI's JSON string value: escapes are decoded first ("\/" is '/', "\u0000" a NUL).
			const std::string escapedSlash = R"({"asset":{"version":"2.0"},"buffers":[{"byteLength":4,"uri":"Sub\/Data.bin"}]})";
			Result<std::vector<std::string>> unescaped = GltfImporter::ListExternalUris(AsBytes(escapedSlash));
			REQUIRE_MESSAGE(unescaped.has_value(), unescaped.error().ToString());
			CHECK(*unescaped == std::vector<std::string>{ "Sub/Data.bin" });
			const std::string escapedNul = R"({"asset":{"version":"2.0"},"buffers":[{"byteLength":4,"uri":"Data\u0000.bin"}]})";
			Result<std::vector<std::string>> nul = GltfImporter::ListExternalUris(AsBytes(escapedNul));
			REQUIRE_FALSE(nul.has_value());
			CHECK(nul.error().GetCode() == ErrorCode::ImportFailed);

			// A file cgltf cannot parse is a Parse error.
			const std::string garbage = "this is not glTF";
			Result<std::vector<std::string>> parsed = GltfImporter::ListExternalUris(AsBytes(garbage));
			REQUIRE_FALSE(parsed.has_value());
			CHECK(parsed.error().GetCode() == ErrorCode::Parse);
		}

		TEST_CASE("GltfImporter: TEXCOORD_1 and COLOR_0 raise their diagnostics")
		{
			Test::AssetTestFixture fixture;
			CopyGltfFixtures(fixture);
			Result<ImportResult> occlusion = ImportGltf(fixture, "Assets/Models/TexCoord1Occlusion.gltf", MakeGltfMetadata(AssetHandle(0xf1)));
			REQUIRE_MESSAGE(occlusion.has_value(), occlusion.error().ToString());
			REQUIRE(occlusion->Diagnostics.size() == 1);
			CHECK(occlusion->Diagnostics.front().Code == AssetUnsupportedUvSetCode);
			CHECK(occlusion->Diagnostics.front().Severity == DiagnosticSeverity::Warning);
			CHECK(occlusion->Diagnostics.front().Path == "Assets/Models/TexCoord1Occlusion.gltf");
			CHECK(occlusion->Diagnostics.front().Asset == AssetHandle(0xf1));
			CHECK(occlusion->Diagnostics.front().Subject == "materials[0].occlusionTexture");
			// The occlusion texture is ignored: the material has no occlusion map, and no texture is imported for it.
			const ImportedArtifact* material = FindArtifact(*occlusion, AssetType::Material);
			REQUIRE(material != nullptr);
			Result<AssetRef<MaterialData>> loaded = LoadCookedMaterial(material->Cooked, fixture.GetRegistry());
			REQUIRE(loaded.has_value());
			CHECK_FALSE((*loaded)->OcclusionMap.IsValid());
			CHECK(FindArtifact(*occlusion, AssetType::Texture) == nullptr);

			Result<ImportResult> colors = ImportGltf(fixture, "Assets/Models/VertexColors.gltf", MakeGltfMetadata(AssetHandle(0xf2)));
			REQUIRE_MESSAGE(colors.has_value(), colors.error().ToString());
			REQUIRE(colors->Diagnostics.size() == 1);
			CHECK(colors->Diagnostics.front().Code == AssetVertexColorsIgnoredCode);
			CHECK(colors->Diagnostics.front().Subject == "meshes[0].primitives[0]");
			CHECK(colors->Diagnostics.front().Path == "Assets/Models/VertexColors.gltf");
		}

		TEST_CASE("GltfImporter: an image with its own Texture meta is referenced, not duplicated")
		{
			Test::AssetTestFixture fixture;
			CopyGltfFixtures(fixture);
			const AssetHandle standalone(0x5a5a000000000001ull);
			const std::vector<ImportAssetLookupEntry> assets = {
				{ .SourcePath = fixture.ProjectPath("Assets/Models/Textures/Shared.png"), .Handle = standalone, .Kind = AssetMetaKind::Asset, .Type = AssetType::Texture, .Owner = AssetHandle() },
			};
			GltfImportRun run = RunGltfImport(fixture, "Assets/Models/StandaloneTexture.gltf", MakeGltfMetadata(AssetHandle(0x51)), assets);
			Result<ImportResult>& imported = run.Imported;
			REQUIRE_MESSAGE(imported.has_value(), imported.error().ToString());
			// No texture sub-asset: the material references the standalone texture, which becomes a dependency.
			CHECK(FindArtifact(*imported, AssetType::Texture) == nullptr);
			CHECK(std::ranges::find(imported->Dependencies, standalone) != imported->Dependencies.end());
			const ImportedArtifact* material = FindArtifact(*imported, AssetType::Material);
			REQUIRE(material != nullptr);
			Result<AssetRef<MaterialData>> loaded = LoadCookedMaterial(material->Cooked, fixture.GetRegistry());
			REQUIRE(loaded.has_value());
			CHECK((*loaded)->BaseColorMap.GetHandle() == standalone);
			// The image was looked up by path, never read.
			REQUIRE(run.Lookups.size() == 1);
			CHECK(run.Lookups.front().Path == fixture.ProjectPath("Assets/Models/Textures/Shared.png"));
			CHECK(run.Lookups.front().Found == assets.front());
			CHECK(run.Reads.empty());

			// Without the standalone meta the same image becomes a texture sub-asset.
			GltfImportRun embedded = RunGltfImport(fixture, "Assets/Models/StandaloneTexture.gltf", MakeGltfMetadata(AssetHandle(0x52)));
			REQUIRE(embedded.Imported.has_value());
			CHECK(FindArtifact(*embedded.Imported, AssetType::Texture) != nullptr);
			CHECK(embedded.Imported->Dependencies.empty());
			REQUIRE(embedded.Reads.size() == 1);
			CHECK(embedded.Reads.front().Path == fixture.ProjectPath("Assets/Models/Textures/Shared.png"));

			// A dependency meta at the image's path is no standalone texture: the image is still imported as a sub-asset.
			const std::vector<ImportAssetLookupEntry> dependency = {
				{ .SourcePath = fixture.ProjectPath("Assets/Models/Textures/Shared.png"), .Handle = AssetHandle(0x5a5a000000000002ull), .Kind = AssetMetaKind::Dependency, .Type = AssetType::None, .Owner = AssetHandle(0x53) },
			};
			Result<ImportResult> owned = ImportGltf(fixture, "Assets/Models/StandaloneTexture.gltf", MakeGltfMetadata(AssetHandle(0x53)), dependency);
			REQUIRE(owned.has_value());
			CHECK(FindArtifact(*owned, AssetType::Texture) != nullptr);
		}

		TEST_CASE("GltfImporter: Import reads every external buffer and the images its materials use")
		{
			Test::AssetTestFixture fixture;
			CopyGltfFixtures(fixture);
			GltfImportRun textured = RunGltfImport(fixture, "Assets/Models/Textured.gltf", MakeGltfMetadata(AssetHandle(0x91)));
			REQUIRE_MESSAGE(textured.Imported.has_value(), textured.Imported.error().ToString());
			REQUIRE(textured.Reads.size() == 2);
			CHECK(textured.Reads[0].Path == fixture.ProjectPath("Assets/Models/Textured.bin"));
			CHECK(textured.Reads[0].Hash == XXH64(fixture.ReadProjectFile("Assets/Models/Textured.bin")));
			CHECK(textured.Reads[1].Path == fixture.ProjectPath("Assets/Models/Textures/Checker.png"));
			CHECK(textured.Reads[1].Hash == XXH64(fixture.ReadProjectFile("Assets/Models/Textures/Checker.png")));

			// Embedded data (a .glb with a buffer-view image, data URIs) reads nothing.
			for (const std::string_view name : { "Box.glb", "DataUri.gltf" })
			{
				CAPTURE(std::string(name));
				GltfImportRun embedded = RunGltfImport(fixture, "Assets/Models/" + std::string(name), MakeGltfMetadata(AssetHandle(0x92)));
				REQUIRE_MESSAGE(embedded.Imported.has_value(), embedded.Imported.error().ToString());
				CHECK(embedded.Reads.empty());
				CHECK(GetKeys(*embedded.Imported, AssetType::Texture) == std::vector<std::string>{ "texture:0" });
			}

			// A missing external buffer fails with the VFS error, naming the buffer and the source.
			Buffer bytes = fixture.ReadProjectFile("Assets/Models/Textured.gltf");
			Result<Json> document = JsonReader::Parse(AsStringView(bytes));
			REQUIRE(document.has_value());
			(*document)["buffers"][0]["uri"] = "Missing.bin";
			const Result<ImportResult> missing = ImportDocument(fixture, "MissingBuffer.gltf", *document);
			REQUIRE_FALSE(missing.has_value());
			CHECK(missing.error().GetCode() == ErrorCode::NotFound);
			CHECK(missing.error().ToString().find("buffers[0]") != std::string::npos);
			CHECK(missing.error().ToString().find("Assets/Models/MissingBuffer.gltf") != std::string::npos);
		}

		TEST_CASE("GltfImporter: generated tangents agree with the file's tangents")
		{
			Test::AssetTestFixture fixture;
			CopyGltfFixtures(fixture);
			Result<ImportResult> withTangents = ImportGltf(fixture, "Assets/Models/NormalMapped.gltf", MakeGltfMetadata(AssetHandle(0x61)));
			Result<ImportResult> generated = ImportGltf(fixture, "Assets/Models/NormalMappedNoTangents.gltf", MakeGltfMetadata(AssetHandle(0x62)));
			REQUIRE_MESSAGE(withTangents.has_value(), withTangents.error().ToString());
			REQUIRE_MESSAGE(generated.has_value(), generated.error().ToString());
			// The fixtures share their geometry; the generator writes MikkTSpace tangents into NormalMapped.gltf.
			const AssetRef<MeshData> fileMesh = LoadMesh(FindArtifact(*withTangents, AssetType::Mesh));
			const AssetRef<MeshData> generatedMesh = LoadMesh(FindArtifact(*generated, AssetType::Mesh));
			REQUIRE(fileMesh->Vertices.size() == generatedMesh->Vertices.size());
			for (size_t index = 0; index < fileMesh->Vertices.size(); ++index)
			{
				const glm::vec4 expected = fileMesh->Vertices[index].Tangent;
				const glm::vec4 actual = generatedMesh->Vertices[index].Tangent;
				CHECK(glm::dot(glm::vec3(expected), glm::vec3(actual)) == doctest::Approx(1.0f).epsilon(1e-3));
				CHECK(expected.w == actual.w);
			}
			CHECK(generated->Diagnostics.empty());
			// The quad's tangent runs along +u (+X) and its bitangent along -v (+Y, up in the image): sign +1 (glTF).
			CHECK(Test::ApproxEqual(generatedMesh->Vertices.front().Tangent, glm::vec4(1.0f, 0.0f, 0.0f, 1.0f), 1e-5f));
		}

		TEST_CASE("GltfImporter: missing normals are generated and tangents without UVs are approximated")
		{
			Test::AssetTestFixture fixture;
			CopyGltfFixtures(fixture);
			Result<ImportResult> bare = ImportGltf(fixture, "Assets/Models/NoNormalsNoUvs.gltf", MakeGltfMetadata(AssetHandle(0x63)));
			REQUIRE_MESSAGE(bare.has_value(), bare.error().ToString());
			const AssetRef<MeshData> mesh = LoadMesh(FindArtifact(*bare, AssetType::Mesh));
			REQUIRE(mesh->Vertices.size() == 4);
			for (const MeshVertex& vertex : mesh->Vertices)
			{
				CHECK(Test::ApproxEqual(vertex.Normal, glm::vec3(0.0f, 0.0f, 1.0f)));
				CHECK(Test::ApproxEqual(vertex.Tangent, glm::vec4(1.0f, 0.0f, 0.0f, 1.0f)));
				CHECK(vertex.TexCoord == glm::vec2(0.0f));
			}
			// No material: the slot uses the built-in Default material.
			REQUIRE(mesh->Slots.size() == 1);
			CHECK(mesh->Slots.front().Name == "Default");
			CHECK_FALSE(mesh->Slots.front().DefaultMaterial.IsValid());
			CHECK(GetDiagnosticSubjects(*bare, AssetTangentsApproximatedCode) == std::vector<std::string>{ "meshes[0].primitives[0]" });
			REQUIRE(bare->Diagnostics.size() == 1);
			CHECK(bare->Diagnostics.front().Severity == DiagnosticSeverity::Warning);

			// With tangent generation off, the perpendicular basis is what was asked for: no diagnostic.
			Result<ImportResult> quiet = ImportGltf(fixture, "Assets/Models/NoNormalsNoUvs.gltf",
				MakeGltfMetadata(AssetHandle(0x64), "GenerateMissingTangents", Json(false)));
			REQUIRE_MESSAGE(quiet.has_value(), quiet.error().ToString());
			CHECK(quiet->Diagnostics.empty());
		}

		TEST_CASE("GltfImporter: ListExternalUris returns the dependency closure in glTF order")
		{
			Test::AssetTestFixture fixture;
			CopyGltfFixtures(fixture);
			Result<std::vector<std::string>> uris = GltfImporter::ListExternalUris(fixture.ReadProjectFile("Assets/Models/Textured.gltf"));
			REQUIRE_MESSAGE(uris.has_value(), uris.error().ToString());
			CHECK(*uris == std::vector<std::string>{ "Textured.bin", "Textures/Checker.png" });
			Result<std::vector<std::string>> embedded = GltfImporter::ListExternalUris(fixture.ReadProjectFile("Assets/Models/DataUri.gltf"));
			REQUIRE(embedded.has_value());
			CHECK(embedded->empty());
			Result<std::vector<std::string>> glb = GltfImporter::ListExternalUris(fixture.ReadProjectFile("Assets/Models/Box.glb"));
			REQUIRE_MESSAGE(glb.has_value(), glb.error().ToString());
			CHECK(glb->empty());

			// Decoded paths: exactly what Import reads and asset.import copies.
			Result<std::vector<std::string>> encoded = GltfImporter::ListExternalUris(fixture.ReadProjectFile("Assets/Models/EncodedUri.gltf"));
			REQUIRE_MESSAGE(encoded.has_value(), encoded.error().ToString());
			CHECK(*encoded == std::vector<std::string>{ "Encoded Data/Box.bin" });
			GltfImportRun imported = RunGltfImport(fixture, "Assets/Models/EncodedUri.gltf", MakeGltfMetadata(AssetHandle(0x71)));
			REQUIRE_MESSAGE(imported.Imported.has_value(), imported.Imported.error().ToString());
			REQUIRE(imported.Reads.size() == 1);
			CHECK(imported.Reads.front().Path == fixture.ProjectPath("Assets/Models/Encoded Data/Box.bin"));

			// ListDependencyFiles resolves them against the source's directory, sorted.
			Result<std::vector<VfsPath>> files = GltfImporter().ListDependencyFiles(fixture.ReadProjectFile("Assets/Models/Textured.gltf"),
				fixture.ProjectPath("Assets/Models/Textured.gltf"));
			REQUIRE_MESSAGE(files.has_value(), files.error().ToString());
			CHECK(*files == std::vector<VfsPath>{ fixture.ProjectPath("Assets/Models/Textured.bin"), fixture.ProjectPath("Assets/Models/Textures/Checker.png") });
			Result<std::vector<VfsPath>> rejected = GltfImporter().ListDependencyFiles(fixture.ReadProjectFile("Assets/Models/ParentEscape.gltf"),
				fixture.ProjectPath("Assets/Models/ParentEscape.gltf"));
			REQUIRE_FALSE(rejected.has_value());
			CHECK(rejected.error().GetCode() == ErrorCode::ImportFailed);
			// A decoded path the VFS does not accept (a reserved device name) is rejected too.
			const std::string device = MakeUriDocument("nul.bin").dump();
			Result<std::vector<VfsPath>> reserved = GltfImporter().ListDependencyFiles(AsBytes(device), fixture.ProjectPath("Assets/Models/Device.gltf"));
			REQUIRE_FALSE(reserved.has_value());
			CHECK(reserved.error().GetCode() == ErrorCode::ImportFailed);
			CHECK(reserved.error().ToString().find("nul.bin") != std::string::npos);
		}

		TEST_CASE("GltfImporter: Scale is baked into the meshes and node translations, not the root transform")
		{
			Test::AssetTestFixture fixture;
			CopyGltfFixtures(fixture);
			Result<ImportResult> unit = ImportGltf(fixture, "Assets/Models/Box.gltf", MakeGltfMetadata(AssetHandle(0x81)));
			AssetMetadata scaledMetadata = MakeGltfMetadata(AssetHandle(0x81));
			Json settings = MakeDefaultSettings();
			settings["Scale"] = 0.5;
			scaledMetadata.Settings = VariantValue(std::move(settings));
			Result<ImportResult> scaled = ImportGltf(fixture, "Assets/Models/Box.gltf", scaledMetadata);
			REQUIRE_MESSAGE(unit.has_value(), unit.error().ToString());
			REQUIRE_MESSAGE(scaled.has_value(), scaled.error().ToString());

			Result<AssetRef<MeshData>> unitMesh = LoadCookedMesh(FindArtifact(*unit, AssetType::Mesh)->Cooked);
			Result<AssetRef<MeshData>> scaledMesh = LoadCookedMesh(FindArtifact(*scaled, AssetType::Mesh)->Cooked);
			REQUIRE(unitMesh.has_value());
			REQUIRE(scaledMesh.has_value());
			REQUIRE((*unitMesh)->Vertices.size() == (*scaledMesh)->Vertices.size());
			for (size_t index = 0; index < (*unitMesh)->Vertices.size(); ++index)
			{
				CHECK((*scaledMesh)->Vertices[index].Position == (*unitMesh)->Vertices[index].Position * 0.5f);
				CHECK((*scaledMesh)->Vertices[index].Normal == (*unitMesh)->Vertices[index].Normal);
			}
			CHECK((*scaledMesh)->Bounds.Min == (*unitMesh)->Bounds.Min * 0.5f);
			CHECK((*scaledMesh)->Bounds.Max == (*unitMesh)->Bounds.Max * 0.5f);

			// The prefab root keeps an identity Transform: every instance overrides the root's Transform implicitly (§5.5).
			Result<AssetRef<PrefabData>> prefab = LoadCookedPrefab(scaled->Artifacts.front().Cooked);
			REQUIRE(prefab.has_value());
			const Json& document = *(*prefab)->Document;
			const Json::json_pointer rootScale("/Entities/0/Components/Transform/Scale");
			REQUIRE(document.contains(rootScale));
			CHECK(document[rootScale] == Json::array({ 1, 1, 1 }));

			// Node translations are scaled too (Hierarchy.gltf: "Base" at (0, 1, 0), "Left" at (-2, 0, 0) with scale 2).
			Result<ImportResult> hierarchy = ImportGltf(fixture, "Assets/Models/Hierarchy.gltf", MakeGltfMetadata(AssetHandle(0x82), "Scale", Json(0.5)));
			REQUIRE_MESSAGE(hierarchy.has_value(), hierarchy.error().ToString());
			const Json nodes = LoadPrefabDocument(*hierarchy);
			CHECK(ReadTransform(fixture, FindEntity(nodes, "Base")).Translation == glm::vec3(0.0f, 0.5f, 0.0f));
			const TransformComponent left = ReadTransform(fixture, FindEntity(nodes, "Left"));
			CHECK(left.Translation == glm::vec3(-1.0f, 0.0f, 0.0f));
			CHECK(left.Scale == glm::vec3(2.0f));
		}

		TEST_CASE("GltfImporter: names are decoded from JSON and sanitized per character in keys")
		{
			Test::AssetTestFixture fixture;
			CopyGltfFixtures(fixture);
			const Buffer box = fixture.ReadProjectFile("Assets/Models/Box.gltf");
			std::string text(AsStringView(box));
			const std::string_view original = R"("name": "Box")";
			const std::string_view escaped = R"("name": "Café \/ 1")";
			size_t replaced = 0;
			for (size_t found = text.find(original); found != std::string::npos; found = text.find(original, found + escaped.size()))
			{
				text.replace(found, original.size(), escaped);
				++replaced;
			}
			REQUIRE(replaced == 2); // the mesh and the node
			fixture.WriteProjectText("Assets/Models/Named.gltf", text);
			const AssetHandle source(0x6e6e000000000001ull);
			Result<ImportResult> imported = ImportGltf(fixture, "Assets/Models/Named.gltf", MakeGltfMetadata(source));
			REQUIRE_MESSAGE(imported.has_value(), imported.error().ToString());
			// "Café / 1": the é (two UTF-8 bytes), both spaces and the slash each become one '_'.
			CHECK(GetKeys(*imported, AssetType::Mesh) == std::vector<std::string>{ "mesh:0:Caf____1" });
			const Json document = LoadPrefabDocument(*imported);
			CHECK(document["Entities"][1]["Name"] == Json("Caf\xC3\xA9 / 1"));
		}

		TEST_CASE("GltfImporter: the prefab mirrors the default scene's node hierarchy with stable entity IDs")
		{
			Test::AssetTestFixture fixture;
			CopyGltfFixtures(fixture);
			const AssetHandle source(0x4e4e000000000001ull);
			Result<ImportResult> imported = ImportGltf(fixture, "Assets/Models/Hierarchy.gltf", MakeGltfMetadata(source));
			REQUIRE_MESSAGE(imported.has_value(), imported.error().ToString());
			CHECK(GetKeys(*imported, AssetType::Mesh) == std::vector<std::string>{ "mesh:0:Cube" });
			const AssetHandle cube = DeriveSubAssetHandle(source, "mesh:0:Cube");
			const Json document = LoadPrefabDocument(*imported);

			// The default scene is "scene": 1, so "Unused" (scene 0 only) is absent. Canonical order: the root, then depth
			// first with children in glTF order; an unnamed node is "Node <index>".
			const auto id = [&source](std::string_view key)
			{
				return Json(UUID(Hash64(source.GetValue(), key)).ToString());
			};
			const Json& entities = document["Entities"];
			REQUIRE(entities.size() == 5);
			const std::array<std::string_view, 5> names = { "Hierarchy", "Base", "Left", "Node 2", "Leaf" };
			const std::array<std::string_view, 5> keys = { "root", "node:0", "node:1", "node:2", "node:3" };
			const std::array<std::string_view, 5> parents = { "", "root", "node:0", "node:0", "node:2" };
			for (size_t index = 0; index < entities.size(); ++index)
			{
				CAPTURE(index);
				CHECK(entities[index]["Name"] == Json(std::string(names[index])));
				CHECK(entities[index]["ID"] == id(keys[index]));
				CHECK(entities[index]["Parent"] == (parents[index].empty() ? Json(nullptr) : id(parents[index])));
				CHECK(entities[index]["Active"] == Json(true));
			}
			CHECK(document["Root"] == id("root"));
			CHECK(document["Name"] == Json("Hierarchy"));

			// Transforms: TRS as written, and a mirroring matrix decomposed into rotation and a negative scale.
			const TransformComponent root = ReadTransform(fixture, entities[0]);
			CHECK(root.Translation == glm::vec3(0.0f));
			CHECK(root.Scale == glm::vec3(1.0f));
			const TransformComponent left = ReadTransform(fixture, entities[2]);
			CHECK(left.Translation == glm::vec3(-2.0f, 0.0f, 0.0f));
			CHECK(left.Scale == glm::vec3(2.0f));
			CHECK(Test::ApproxEqual(left.Rotation, glm::quat(0.70710678f, 0.0f, 0.70710678f, 0.0f), 1e-6f));
			const TransformComponent mirrored = ReadTransform(fixture, entities[3]);
			CHECK(mirrored.Translation == glm::vec3(3.0f, 0.0f, 0.0f));
			CHECK(mirrored.Scale == glm::vec3(-1.0f, 1.0f, 1.0f));
			glm::mat3 scale(1.0f);
			scale[0][0] = mirrored.Scale.x;
			scale[1][1] = mirrored.Scale.y;
			scale[2][2] = mirrored.Scale.z;
			const glm::mat3 composed = glm::mat3_cast(mirrored.Rotation) * scale;
			CHECK(Test::ApproxEqual(composed, glm::mat3(1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, -1.0f), 1e-6f));

			// Mesh renderers on the nodes with a mesh only.
			const std::array<bool, 5> drawn = { false, false, true, true, false };
			for (size_t index = 0; index < entities.size(); ++index)
			{
				CAPTURE(index);
				CHECK(ReadRendererMesh(fixture, entities[index]) == (drawn[index] ? cube : AssetHandle()));
			}
			CHECK(document["ComponentVersions"].contains("Transform"));
			CHECK(document["ComponentVersions"].contains("MeshRenderer"));

			// The document is canonical: the prefab loader accepts it strictly and writes it back unchanged.
			LoadReport report;
			LoadOptions options;
			options.StrictUnknowns = true;
			Result<Prefab> prefab = Prefab::FromJson(document, fixture.GetRegistry(), options, report);
			REQUIRE_MESSAGE(prefab.has_value(), prefab.error().ToString());
			CHECK(report.Diagnostics.empty());
			Result<std::string> written = prefab->SaveToString(JsonStyle::Minified);
			Result<std::string> cooked = JsonWriter::Write(document, JsonStyle::Minified);
			REQUIRE(written.has_value());
			REQUIRE(cooked.has_value());
			CHECK(*written == *cooked);
		}

		TEST_CASE("GltfImporter: MergeMeshes merges every mesh instance of the scene into mesh:merged")
		{
			Test::AssetTestFixture fixture;
			CopyGltfFixtures(fixture);
			const AssetHandle source(0x4e4e000000000002ull);
			Result<ImportResult> imported = ImportGltf(fixture, "Assets/Models/Hierarchy.gltf", MakeGltfMetadata(source, "MergeMeshes", Json(true)));
			REQUIRE_MESSAGE(imported.has_value(), imported.error().ToString());
			CHECK(GetKeys(*imported, AssetType::Mesh) == std::vector<std::string>{ "mesh:merged" });
			const AssetRef<MeshData> merged = LoadMesh(FindArtifact(*imported, "mesh:merged"));

			// "Left" (scale 2 at (-2, 1, 0)) and "Node 2" (mirrored, at (3, 1, 0)); "Unused" is not in the default scene.
			REQUIRE(merged->Submeshes.size() == 2);
			CHECK(Test::ApproxEqual(merged->Bounds.Min, glm::vec3(-3.0f, 0.0f, -1.0f), 1e-5f));
			CHECK(Test::ApproxEqual(merged->Bounds.Max, glm::vec3(3.5f, 2.0f, 1.0f), 1e-5f));
			REQUIRE(merged->Slots.size() == 2);
			CHECK(merged->Slots[0].Name == "Paint");
			CHECK(merged->Slots[0].DefaultMaterial == DeriveSubAssetHandle(source, "material:0:Paint"));

			// Every triangle still faces along its vertices' normals, the mirrored instance included (winding flipped).
			for (size_t corner = 0; corner + 2 < merged->Indices.size(); corner += 3)
			{
				const MeshVertex& a = merged->Vertices[merged->Indices[corner]];
				const MeshVertex& b = merged->Vertices[merged->Indices[corner + 1]];
				const MeshVertex& c = merged->Vertices[merged->Indices[corner + 2]];
				CHECK(glm::dot(glm::cross(b.Position - a.Position, c.Position - a.Position), a.Normal) > 0.0f);
			}

			// The prefab root draws the merged mesh; the node entities stay, without renderers.
			const Json document = LoadPrefabDocument(*imported);
			const Json& entities = document["Entities"];
			REQUIRE(entities.size() == 5);
			CHECK(ReadRendererMesh(fixture, entities[0]) == DeriveSubAssetHandle(source, "mesh:merged"));
			for (size_t index = 1; index < entities.size(); ++index)
				CHECK_FALSE(entities[index]["Components"].contains("MeshRenderer"));
			LoadReport report;
			CHECK(Prefab::FromJson(document, fixture.GetRegistry(), LoadOptions{}, report).has_value());
		}

		TEST_CASE("GltfImporter: strips and fans become triangle lists, points and lines are skipped")
		{
			Test::AssetTestFixture fixture;
			CopyGltfFixtures(fixture);
			Result<ImportResult> imported = ImportGltf(fixture, "Assets/Models/PrimitiveModes.gltf", MakeGltfMetadata(AssetHandle(0xb1)));
			REQUIRE_MESSAGE(imported.has_value(), imported.error().ToString());
			const AssetRef<MeshData> mesh = LoadMesh(FindArtifact(*imported, AssetType::Mesh));
			// The strip and the fan give two triangles each; the list keeps its one non-degenerate triangle.
			REQUIRE(mesh->Submeshes.size() == 3);
			CHECK(mesh->Submeshes[0].IndexCount == 6);
			CHECK(mesh->Submeshes[1].IndexCount == 6);
			CHECK(mesh->Submeshes[2].IndexCount == 3);
			CHECK(mesh->Vertices.size() == 11);
			for (size_t corner = 0; corner + 2 < mesh->Indices.size(); corner += 3)
			{
				const glm::vec3 a = mesh->Vertices[mesh->Indices[corner]].Position;
				const glm::vec3 b = mesh->Vertices[mesh->Indices[corner + 1]].Position;
				const glm::vec3 c = mesh->Vertices[mesh->Indices[corner + 2]].Position;
				CHECK(glm::cross(b - a, c - a).z > 0.0f);
			}
			CHECK(GetDiagnosticSubjects(*imported, AssetContentSkippedCode) == std::vector<std::string>{ "meshes[0].primitives[2]", "meshes[0].primitives[3]" });
			CHECK(imported->Diagnostics.size() == 2);
		}

		TEST_CASE("GltfImporter: skins, animations, cameras and lights are skipped with ASSET_CONTENT_SKIPPED")
		{
			Test::AssetTestFixture fixture;
			CopyGltfFixtures(fixture);
			Result<ImportResult> imported = ImportGltf(fixture, "Assets/Models/SkippedContent.gltf", MakeGltfMetadata(AssetHandle(0xc1)));
			REQUIRE_MESSAGE(imported.has_value(), imported.error().ToString());
			CHECK(GetDiagnosticSubjects(*imported, AssetContentSkippedCode) == std::vector<std::string>{ "skins[0]", "animations[0]", "cameras[0]", "KHR_lights_punctual.lights[0]" });
			for (const AssetDiagnostic& diagnostic : imported->Diagnostics)
			{
				CHECK(diagnostic.Severity == DiagnosticSeverity::Warning);
				CHECK(diagnostic.Asset == AssetHandle(0xc1));
				CHECK(diagnostic.Path == "Assets/Models/SkippedContent.gltf");
				CHECK_FALSE(diagnostic.Message.empty());
			}
			// The nodes that held them are still entities.
			const Json document = LoadPrefabDocument(*imported);
			CHECK(document["Entities"].size() == 5);
			CHECK(FindEntity(document, "Camera")["Components"].contains("Transform"));
		}

		TEST_CASE("GltfImporter: materials carry factors, emissive strength, the texture transform and texture slots")
		{
			Test::AssetTestFixture fixture;
			CopyGltfFixtures(fixture);
			const AssetHandle source(0x3a3a000000000001ull);
			Result<ImportResult> imported = ImportGltf(fixture, "Assets/Models/Materials.gltf", MakeGltfMetadata(source));
			REQUIRE_MESSAGE(imported.has_value(), imported.error().ToString());
			CHECK(imported->Diagnostics.empty());
			CHECK(imported->Dependencies.empty());
			// One sub-asset per (image, use): the base colour image also serves as emissive, the data image twice as linear.
			CHECK(GetKeys(*imported, AssetType::Texture) == std::vector<std::string>{ "texture:0", "texture:1:normal", "texture:2:linear" });
			CHECK(GetKeys(*imported, AssetType::Material) == std::vector<std::string>{ "material:0:Everything" });

			const AssetRef<MaterialData> material = LoadMaterial(fixture, FindArtifact(*imported, AssetType::Material));
			CHECK(material->BaseColor == glm::vec4(0.5f, 0.25f, 1.0f, 1.0f));
			CHECK(material->Metallic == 0.25f);
			CHECK(material->Roughness == 0.75f);
			CHECK(material->NormalScale == 0.5f);
			CHECK(material->OcclusionStrength == 0.75f);
			CHECK(material->Emissive == glm::vec3(1.0f, 0.5f, 0.25f));
			CHECK(material->EmissiveStrength == 4.0f);
			CHECK(material->AlphaMode == AlphaMode::Mask);
			CHECK(material->AlphaCutoff == 0.75f);
			CHECK(material->DoubleSided);
			CHECK(material->UVScale == glm::vec2(2.0f, 3.0f));
			CHECK(material->UVOffset == glm::vec2(0.25f, 0.5f));
			CHECK(material->BaseColorMap.GetHandle() == DeriveSubAssetHandle(source, "texture:0"));
			CHECK(material->EmissiveMap.GetHandle() == DeriveSubAssetHandle(source, "texture:0"));
			CHECK(material->NormalMap.GetHandle() == DeriveSubAssetHandle(source, "texture:1:normal"));
			CHECK(material->MetallicRoughnessMap.GetHandle() == DeriveSubAssetHandle(source, "texture:2:linear"));
			CHECK(material->OcclusionMap.GetHandle() == DeriveSubAssetHandle(source, "texture:2:linear"));

			// Colour data is sRGB, the other uses are linear.
			const std::pair<std::string_view, TextureFormat> formats[] = { { "texture:0", TextureFormat::RGBA8Srgb },
				{ "texture:1:normal", TextureFormat::RGBA8Unorm }, { "texture:2:linear", TextureFormat::RGBA8Unorm } };
			for (const auto& [key, format] : formats)
			{
				CAPTURE(std::string(key));
				const ImportedArtifact* texture = FindArtifact(*imported, key);
				REQUIRE(texture != nullptr);
				Result<AssetRef<TextureData>> loaded = LoadCookedTexture(texture->Cooked);
				REQUIRE_MESSAGE(loaded.has_value(), loaded.error().ToString());
				CHECK((*loaded)->Format == format);
			}

			// The mesh's slot defaults to the material sub-asset.
			const AssetRef<MeshData> mesh = LoadMesh(FindArtifact(*imported, AssetType::Mesh));
			REQUIRE(mesh->Slots.size() == 1);
			CHECK(mesh->Slots.front().Name == "Everything");
			CHECK(mesh->Slots.front().DefaultMaterial == DeriveSubAssetHandle(source, "material:0:Everything"));
		}

		TEST_CASE("GltfImporter: ImportMaterials off imports no material or texture")
		{
			Test::AssetTestFixture fixture;
			CopyGltfFixtures(fixture);
			GltfImportRun run = RunGltfImport(fixture, "Assets/Models/Textured.gltf", MakeGltfMetadata(AssetHandle(0x95), "ImportMaterials", Json(false)));
			REQUIRE_MESSAGE(run.Imported.has_value(), run.Imported.error().ToString());
			CHECK(FindArtifact(*run.Imported, AssetType::Material) == nullptr);
			CHECK(FindArtifact(*run.Imported, AssetType::Texture) == nullptr);
			const AssetRef<MeshData> mesh = LoadMesh(FindArtifact(*run.Imported, AssetType::Mesh));
			REQUIRE(mesh->Slots.size() == 2);
			CHECK(mesh->Slots[0].Name == "Checker");
			CHECK(mesh->Slots[1].Name == "Trim");
			CHECK_FALSE(mesh->Slots[0].DefaultMaterial.IsValid());
			CHECK_FALSE(mesh->Slots[1].DefaultMaterial.IsValid());
			// The image is not needed, so it is not read; the buffer is.
			REQUIRE(run.Reads.size() == 1);
			CHECK(run.Reads.front().Path == fixture.ProjectPath("Assets/Models/Textured.bin"));
		}

		TEST_CASE("GltfImporter: invalid documents fail with a located, precise error")
		{
			Test::AssetTestFixture fixture;
			CopyGltfFixtures(fixture);

			SUBCASE("a sheared node matrix")
			{
				Json document = ReadBoxDocument(fixture);
				document["nodes"][0]["matrix"] = Json::array({ 1, 0, 0, 0, 0.5, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1 });
				CheckImportFails(ImportDocument(fixture, "Sheared.gltf", document), ErrorCode::ImportFailed,
					{ "nodes[0]", "shear", "Assets/Models/Sheared.gltf" });
			}
			SUBCASE("a projective node matrix")
			{
				Json document = ReadBoxDocument(fixture);
				document["nodes"][0]["matrix"] = Json::array({ 1, 0, 0, 0.5, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1 });
				CheckImportFails(ImportDocument(fixture, "Projective.gltf", document), ErrorCode::ImportFailed, { "nodes[0]", "projective" });
			}
			SUBCASE("a zero rotation")
			{
				Json document = ReadBoxDocument(fixture);
				document["nodes"][0]["rotation"] = Json::array({ 0, 0, 0, 0 });
				CheckImportFails(ImportDocument(fixture, "ZeroRotation.gltf", document), ErrorCode::ImportFailed, { "nodes[0]", "rotation" });
			}
			SUBCASE("an index beyond the vertices")
			{
				const std::array<glm::vec3, 3> positions = { glm::vec3(0.0f), glm::vec3(1.0f, 0.0f, 0.0f), glm::vec3(0.0f, 1.0f, 0.0f) };
				const std::array<uint16_t, 3> indices = { 0, 1, 7 };
				CheckImportFails(ImportDocument(fixture, "IndexRange.gltf", MakeTriangleDocument(positions, indices)), ErrorCode::ImportFailed,
					{ "index", "Assets/Models/IndexRange.gltf" });
			}
			SUBCASE("a position that is not finite")
			{
				const std::array<glm::vec3, 3> positions = { glm::vec3(0.0f), glm::vec3(std::numeric_limits<float>::quiet_NaN(), 0.0f, 0.0f),
					glm::vec3(0.0f, 1.0f, 0.0f) };
				const std::array<uint16_t, 3> indices = { 0, 1, 2 };
				CheckImportFails(ImportDocument(fixture, "NaN.gltf", MakeTriangleDocument(positions, indices)), ErrorCode::ImportFailed,
					{ "meshes[0].primitives[0]", "POSITION", "finite" });
			}
			SUBCASE("a primitive without a non-degenerate triangle")
			{
				const std::array<glm::vec3, 3> positions = { glm::vec3(0.0f), glm::vec3(1.0f, 0.0f, 0.0f), glm::vec3(2.0f, 0.0f, 0.0f) };
				const std::array<uint16_t, 6> indices = { 0, 1, 2, 0, 0, 1 };
				CheckImportFails(ImportDocument(fixture, "Degenerate.gltf", MakeTriangleDocument(positions, indices)), ErrorCode::ImportFailed,
					{ "meshes[0].primitives[0]", "non-degenerate" });
			}
			SUBCASE("a triangle list whose index count is not a multiple of 3")
			{
				const std::array<glm::vec3, 3> positions = { glm::vec3(0.0f), glm::vec3(1.0f, 0.0f, 0.0f), glm::vec3(0.0f, 1.0f, 0.0f) };
				const std::array<uint16_t, 4> indices = { 0, 1, 2, 0 };
				CheckImportFails(ImportDocument(fixture, "Partial.gltf", MakeTriangleDocument(positions, indices)), ErrorCode::ImportFailed,
					{ "meshes[0].primitives[0]", "multiple of 3" });
			}
			// Hostile counts and offsets: cgltf_validate's own size check wraps around for them and then scans the indices
			// far past the buffer (an access violation), and a count without data made the importer allocate until
			// std::bad_alloc. Each is rejected before cgltf reads anything, naming the accessor.
			SUBCASE("an index accessor whose count wraps the required size around")
			{
				const std::array<glm::vec3, 3> positions = { glm::vec3(0.0f), glm::vec3(1.0f, 0.0f, 0.0f), glm::vec3(0.0f, 1.0f, 0.0f) };
				const std::array<uint16_t, 4> indices = { 0, 1, 2, 0 };
				Json document = MakeTriangleDocument(positions, indices);
				// 4 bytes * (2^62 + 1 - 1) wraps to 0 in 64 bits, so the required size looks like 4 of the view's 8 bytes.
				document["accessors"][1]["componentType"] = 5125;
				document["accessors"][1]["count"] = uint64_t{ 4611686018427387905ull };
				CheckImportFails(ImportDocument(fixture, "IndexOverflow.gltf", document), ErrorCode::ImportFailed,
					{ "accessors[1]", "does not fit", "Assets/Models/IndexOverflow.gltf" });
			}
			SUBCASE("an index accessor without a buffer view and a huge count")
			{
				const std::array<glm::vec3, 3> positions = { glm::vec3(0.0f), glm::vec3(1.0f, 0.0f, 0.0f), glm::vec3(0.0f, 1.0f, 0.0f) };
				const std::array<uint16_t, 3> indices = { 0, 1, 2 };
				Json document = MakeTriangleDocument(positions, indices);
				document["accessors"][1].erase("bufferView");
				document["accessors"][1]["count"] = uint64_t{ 1ull << 40 };
				CheckImportFails(ImportDocument(fixture, "UnbackedIndices.gltf", document), ErrorCode::ImportFailed, { "accessors[1]", "no buffer view" });
			}
			SUBCASE("a POSITION accessor without a buffer view and as many vertices as a mesh can index")
			{
				const std::array<glm::vec3, 3> positions = { glm::vec3(0.0f), glm::vec3(1.0f, 0.0f, 0.0f), glm::vec3(0.0f, 1.0f, 0.0f) };
				const std::array<uint16_t, 3> indices = { 0, 1, 2 };
				Json document = MakeTriangleDocument(positions, indices);
				document["accessors"][0].erase("bufferView");
				document["accessors"][0]["count"] = uint64_t{ std::numeric_limits<uint32_t>::max() };
				CheckImportFails(ImportDocument(fixture, "UnbackedPositions.gltf", document), ErrorCode::ImportFailed, { "accessors[0]", "no buffer view" });
			}
			SUBCASE("a sparse accessor whose count wraps the required size around")
			{
				const std::array<glm::vec3, 3> positions = { glm::vec3(0.0f), glm::vec3(1.0f, 0.0f, 0.0f), glm::vec3(0.0f, 1.0f, 0.0f) };
				const std::array<uint16_t, 3> indices = { 0, 1, 2 };
				Json document = MakeTriangleDocument(positions, indices);
				document["accessors"][0]["sparse"] = { { "count", uint64_t{ 4611686018427387905ull } },
					{ "indices", { { "bufferView", 1 }, { "componentType", 5125 } } }, { "values", { { "bufferView", 0 } } } };
				CheckImportFails(ImportDocument(fixture, "SparseOverflow.gltf", document), ErrorCode::ImportFailed, { "accessors[0].sparse", "count" });
			}
			SUBCASE("sparse values that do not fit in their buffer view")
			{
				const std::array<glm::vec3, 3> positions = { glm::vec3(0.0f), glm::vec3(1.0f, 0.0f, 0.0f), glm::vec3(0.0f, 1.0f, 0.0f) };
				const std::array<uint16_t, 3> indices = { 0, 1, 2 };
				Json document = MakeTriangleDocument(positions, indices);
				// Three 12-byte values in the 6-byte index view.
				document["accessors"][0]["sparse"] = { { "count", 3 }, { "indices", { { "bufferView", 1 }, { "componentType", 5123 } } },
					{ "values", { { "bufferView", 1 } } } };
				CheckImportFails(ImportDocument(fixture, "SparseValues.gltf", document), ErrorCode::ImportFailed, { "accessors[0].sparse.values" });
			}
			SUBCASE("a buffer view beyond the end of its buffer")
			{
				Json document = ReadBoxDocument(fixture);
				document["bufferViews"][0]["byteOffset"] = uint64_t{ 9223372036854775807ull };
				CheckImportFails(ImportDocument(fixture, "ViewRange.gltf", document), ErrorCode::ImportFailed, { "bufferViews[0]", "does not fit" });
			}
			SUBCASE("a buffer shorter than its byteLength")
			{
				Json document = ReadBoxDocument(fixture);
				document["buffers"][0]["uri"] = "data:application/octet-stream;base64,AAAA";
				CheckImportFails(ImportDocument(fixture, "Short.gltf", document), ErrorCode::ImportFailed, { "buffers[0]", "byteLength" });
			}
			SUBCASE("a data URI that is not base64")
			{
				Json document = ReadBoxDocument(fixture);
				document["buffers"][0]["uri"] = "data:application/octet-stream,AAAA";
				CheckImportFails(ImportDocument(fixture, "Plain.gltf", document), ErrorCode::ImportFailed, { "buffers[0]", "base64" });
			}
			SUBCASE("a file that is not glTF")
			{
				fixture.WriteProjectText("Assets/Models/Text.gltf", "this is not glTF");
				CheckImportFails(ImportGltf(fixture, "Assets/Models/Text.gltf", MakeGltfMetadata(AssetHandle(0xf9))), ErrorCode::Parse,
					{ "Assets/Models/Text.gltf" });
			}
			SUBCASE("settings outside their bounds")
			{
				CheckImportFails(ImportGltf(fixture, "Assets/Models/Box.gltf", MakeGltfMetadata(AssetHandle(0xfa), "Scale", Json(0.0))),
					ErrorCode::Validation, { "Scale" });
			}
		}

		TEST_CASE("GltfImporter: the importer's identity and its registered settings")
		{
			const GltfImporter importer;
			CHECK(importer.GetId() == "Gltf");
			CHECK(importer.GetVersion() == 1);
			CHECK(importer.GetMainType() == AssetType::Prefab);
			CHECK(importer.GetSettingsTypeName() == "GltfImportSettings");
			CHECK_FALSE(importer.RequiresMainThread());
			const std::span<const std::string_view> extensions = importer.GetExtensions();
			CHECK(std::vector<std::string_view>(extensions.begin(), extensions.end()) == std::vector<std::string_view>{ ".gltf", ".glb" });

			TypeRegistry registry;
			GltfImporter::RegisterTypes(registry);
			registry.Freeze();
			const StructInfo* settings = registry.FindStruct("GltfImportSettings");
			REQUIRE(settings != nullptr);
			// The documented defaults, every field in declaration order (§6.4).
			const Json defaults = settings->MakeDefaultJson();
			CHECK(defaults.dump() == R"({"Scale":1.0,"GenerateMissingTangents":true,"ImportMaterials":true,"MergeMeshes":false})");
			// Scale must be positive.
			for (const double scale : { 0.0, -1.0 })
			{
				CAPTURE(scale);
				GltfImportSettings value;
				Json json = defaults;
				json["Scale"] = scale;
				CHECK_FALSE(settings->FromJson(&value, JsonReader(json), ReadContext{}).has_value());
			}
			GltfImportSettings value;
			Json json = defaults;
			json["Scale"] = 2.5;
			REQUIRE(settings->FromJson(&value, JsonReader(json), ReadContext{}).has_value());
			CHECK(value.Scale == 2.5f);
		}
	}

}
