#include "TestsPCH.h"

#include "Engine/AssetPipeline/Importers/GltfImporter.h"

#include "Engine/Asset/AssetDiagnostic.h"
#include "Engine/Asset/DocumentData.h"
#include "Engine/Asset/MaterialData.h"
#include "Engine/Asset/MeshData.h"
#include "Engine/Core/FileSystem.h"
#include "Engine/Core/Json/JsonReader.h"
#include "Support/AssetTestFixture.h"
#include "Support/TestData.h"

#include <nlohmann/json.hpp>

#include <algorithm>

// The glTF fixtures are generated by Tests/Data/Generate/MakeGltfFixtures.py into Tests/Data/Assets/Gltf (Roadmap M6):
// Box.gltf (data-URI buffer), Box.glb (binary chunk), Textured.gltf with Textured.bin and Textures/Checker.png (external
// files), NormalMapped.gltf (with TANGENT) and NormalMappedNoTangents.gltf, AlphaModes.gltf, DataUri.gltf (buffer and image
// as data URIs), ParentEscape.gltf ("../Outside.bin"), AbsoluteUri.gltf ("/Models/Box.bin"), DriveLetterUri.gltf
// ("C:/Models/Box.bin"), HttpUri.gltf ("http://example.com/Box.bin"), EncodedParentEscape.gltf ("%2e%2e/Outside.bin"),
// EncodedBackslash.gltf ("..%5COutside.bin"), EncodedAbsolute.gltf ("%2FModels/Box.bin"), EncodedUri.gltf with
// "Encoded Data/Box.bin" (URI "Encoded%20Data/Box.bin"), TexCoord1Occlusion.gltf, VertexColors.gltf, DracoRequired.gltf
// (extensionsRequired KHR_draco_mesh_compression) and StandaloneTexture.gltf with Textures/Shared.png.

namespace Engine {

	namespace {

		// Copies Tests/Data/Assets/Gltf into project://Assets/Models.
		void CopyGltfFixtures(Test::AssetTestFixture& fixture)
		{
			const Result<std::vector<std::string>> files = Test::ListTestDataFiles("Assets/Gltf", { ".gltf", ".glb", ".bin", ".png" });
			REQUIRE_MESSAGE(files.has_value(), files.error().ToString());
			REQUIRE_FALSE(files->empty());
			for (const std::string& file : *files)
			{
				Result<Buffer> bytes = FileSystem::ReadFile(Test::GetTestDataPath(file));
				REQUIRE(bytes.has_value());
				fixture.WriteProjectFile("Assets/Models/" + file.substr(std::string_view("Assets/Gltf/").size()), *bytes);
			}
		}

		Json MakeDefaultSettings()
		{
			Json settings = Json::object();
			settings["Scale"] = 1.0;
			settings["GenerateMissingTangents"] = true;
			settings["ImportMaterials"] = true;
			settings["MergeMeshes"] = false;
			return settings;
		}

		AssetMetadata MakeGltfMetadata(AssetHandle handle, std::vector<SubAssetEntry> previous = {})
		{
			AssetMetadata metadata;
			metadata.Handle = handle;
			metadata.Type = AssetType::Prefab;
			metadata.Importer = std::string(GltfImporter::Id);
			metadata.ImporterVersion = GltfImporter::Version;
			metadata.Settings = VariantValue(MakeDefaultSettings());
			metadata.SubAssets = std::move(previous);
			return metadata;
		}

		Result<ImportResult> ImportGltf(Test::AssetTestFixture& fixture, std::string_view relative, const AssetMetadata& metadata,
			std::span<const ImportAssetLookupEntry> assets = {})
		{
			const Buffer bytes = fixture.ReadProjectFile(relative);
			ImportContext context({
				.Vfs = &fixture.GetVfs(),
				.SourcePath = fixture.ProjectPath(relative),
				.SourceBytes = bytes,
				.Settings = metadata.Settings,
				.Registry = &fixture.GetRegistry(),
				.Assets = assets,
				.EnvironmentBaker = nullptr,
				.ScriptDiagnostics = nullptr,
			});
			return GltfImporter().Import(context, metadata);
		}

		std::vector<SubAssetEntry> ToSubAssets(const ImportResult& result)
		{
			std::vector<SubAssetEntry> subAssets;
			for (const ImportedArtifact& artifact : result.Artifacts)
			{
				if (!artifact.SubAssetKey.empty())
					subAssets.push_back({ .Key = artifact.SubAssetKey, .Handle = artifact.Handle, .Type = artifact.Type });
			}
			return subAssets;
		}

		const ImportedArtifact* FindArtifact(const ImportResult& result, AssetType type)
		{
			const auto found = std::ranges::find_if(result.Artifacts, [type](const ImportedArtifact& artifact)
			{
				return artifact.Type == type;
			});
			return found == result.Artifacts.end() ? nullptr : &*found;
		}

	}

	TEST_SUITE("AssetPipeline")
	{
		TEST_CASE("GltfImporter: every fixture imports" * doctest::skip(true))
		{
			Test::AssetTestFixture fixture;
			CopyGltfFixtures(fixture);
			const std::string_view importable[] = { "Box.gltf", "Box.glb", "Textured.gltf", "NormalMapped.gltf", "NormalMappedNoTangents.gltf",
				"AlphaModes.gltf", "DataUri.gltf", "TexCoord1Occlusion.gltf", "VertexColors.gltf", "StandaloneTexture.gltf" };
			for (const std::string_view name : importable)
			{
				CAPTURE(std::string(name));
				Result<ImportResult> imported = ImportGltf(fixture, "Assets/Models/" + std::string(name), MakeGltfMetadata(AssetHandle(0x9000 + name.size())));
				REQUIRE_MESSAGE(imported.has_value(), imported.error().ToString());
				// The main asset is the prefab, first; then at least one mesh sub-asset, keys sorted.
				REQUIRE_FALSE(imported->Artifacts.empty());
				CHECK(imported->Artifacts.front().Type == AssetType::Prefab);
				CHECK(imported->Artifacts.front().SubAssetKey.empty());
				const ImportedArtifact* mesh = FindArtifact(*imported, AssetType::Mesh);
				REQUIRE(mesh != nullptr);
				Result<AssetRef<MeshData>> loaded = LoadCookedMesh(mesh->Cooked);
				REQUIRE_MESSAGE(loaded.has_value(), loaded.error().ToString());
				CHECK(ValidateMeshData(**loaded).has_value());
				for (size_t index = 2; index < imported->Artifacts.size(); ++index)
					CHECK(imported->Artifacts[index - 1].SubAssetKey < imported->Artifacts[index].SubAssetKey);
				Result<AssetRef<PrefabData>> prefab = LoadCookedPrefab(imported->Artifacts.front().Cooked);
				CHECK(prefab.has_value());
			}

			// The material sub-assets carry the alpha modes (AlphaModes.gltf: OPAQUE, MASK with cutoff 0.25, BLEND).
			Result<ImportResult> alpha = ImportGltf(fixture, "Assets/Models/AlphaModes.gltf", MakeGltfMetadata(AssetHandle(0xa1)));
			REQUIRE(alpha.has_value());
			std::vector<AlphaMode> modes;
			for (const ImportedArtifact& artifact : alpha->Artifacts)
			{
				if (artifact.Type != AssetType::Material)
					continue;
				Result<AssetRef<MaterialData>> material = LoadCookedMaterial(artifact.Cooked, fixture.GetRegistry());
				REQUIRE(material.has_value());
				modes.push_back((*material)->AlphaMode);
			}
			CHECK(modes == std::vector<AlphaMode>{ AlphaMode::Opaque, AlphaMode::Mask, AlphaMode::Blend });
		}

		TEST_CASE("GltfImporter: required Draco extension is rejected with a precise message" * doctest::skip(true))
		{
			Test::AssetTestFixture fixture;
			CopyGltfFixtures(fixture);
			Result<ImportResult> imported = ImportGltf(fixture, "Assets/Models/DracoRequired.gltf", MakeGltfMetadata(AssetHandle(0xd1)));
			REQUIRE_FALSE(imported.has_value());
			CHECK(imported.error().GetCode() == ErrorCode::ImportFailed);
			const std::string message = imported.error().ToString();
			CHECK(message.find("KHR_draco_mesh_compression") != std::string::npos);
			CHECK(message.find("Assets/Models/DracoRequired.gltf") != std::string::npos);
		}

		TEST_CASE("GltfImporter: reimport keeps sub-asset handles" * doctest::skip(true))
		{
			Test::AssetTestFixture fixture;
			CopyGltfFixtures(fixture);
			const AssetHandle source(0x7e7e000000000001ull);
			Result<ImportResult> first = ImportGltf(fixture, "Assets/Models/Textured.gltf", MakeGltfMetadata(source));
			REQUIRE_MESSAGE(first.has_value(), first.error().ToString());
			const std::vector<SubAssetEntry> subAssets = ToSubAssets(*first);
			REQUIRE_FALSE(subAssets.empty());
			for (const SubAssetEntry& entry : subAssets)
				CHECK(entry.Handle == DeriveSubAssetHandle(source, entry.Key));

			// A modified file (the node renamed, a second primitive's data unchanged): the keys, and so the handles, stay.
			Buffer modified = fixture.ReadProjectFile("Assets/Models/Textured.gltf");
			Result<Json> document = JsonReader::Parse(AsStringView(modified));
			REQUIRE(document.has_value());
			(*document)["nodes"][0]["name"] = "RenamedNode";
			fixture.WriteProjectText("Assets/Models/Textured.gltf", document->dump());
			Result<ImportResult> second = ImportGltf(fixture, "Assets/Models/Textured.gltf", MakeGltfMetadata(source, subAssets));
			REQUIRE_MESSAGE(second.has_value(), second.error().ToString());
			CHECK(ToSubAssets(*second) == subAssets);
		}

		TEST_CASE("GltfImporter: parent-escaping, absolute and http URIs are rejected" * doctest::skip(true))
		{
			Test::AssetTestFixture fixture;
			CopyGltfFixtures(fixture);
			struct Case
			{
				std::string_view File;
				std::string_view Uri;
			};
			const Case cases[] = {
				{ "ParentEscape.gltf", "../Outside.bin" },
				{ "AbsoluteUri.gltf", "/Models/Box.bin" },
				{ "DriveLetterUri.gltf", "C:/Models/Box.bin" },
				{ "HttpUri.gltf", "http://example.com/Box.bin" },
				// Percent-encoded escapes are validated after decoding, and named as written.
				{ "EncodedParentEscape.gltf", "%2e%2e/Outside.bin" },
				{ "EncodedBackslash.gltf", "..%5COutside.bin" },
				{ "EncodedAbsolute.gltf", "%2FModels/Box.bin" },
			};
			for (const Case& testCase : cases)
			{
				CAPTURE(std::string(testCase.File));
				Result<ImportResult> imported = ImportGltf(fixture, "Assets/Models/" + std::string(testCase.File), MakeGltfMetadata(AssetHandle(0xe1)));
				REQUIRE_FALSE(imported.has_value());
				CHECK(imported.error().GetCode() == ErrorCode::ImportFailed);
				CHECK(imported.error().ToString().find(testCase.Uri) != std::string::npos);
				// ListExternalUris (asset.import's closure) rejects them the same way.
				Result<std::vector<std::string>> uris = GltfImporter::ListExternalUris(fixture.ReadProjectFile("Assets/Models/" + std::string(testCase.File)));
				REQUIRE_FALSE(uris.has_value());
				CHECK(uris.error().GetCode() == ErrorCode::ImportFailed);
			}
		}

		TEST_CASE("GltfImporter: TEXCOORD_1 and COLOR_0 raise their diagnostics" * doctest::skip(true))
		{
			Test::AssetTestFixture fixture;
			CopyGltfFixtures(fixture);
			Result<ImportResult> occlusion = ImportGltf(fixture, "Assets/Models/TexCoord1Occlusion.gltf", MakeGltfMetadata(AssetHandle(0xf1)));
			REQUIRE_MESSAGE(occlusion.has_value(), occlusion.error().ToString());
			REQUIRE(occlusion->Diagnostics.size() == 1);
			CHECK(occlusion->Diagnostics.front().Code == AssetUnsupportedUvSetCode);
			CHECK(occlusion->Diagnostics.front().Severity == DiagnosticSeverity::Warning);
			CHECK(occlusion->Diagnostics.front().Path == "Assets/Models/TexCoord1Occlusion.gltf");
			// The occlusion texture is ignored: the material has no occlusion map.
			const ImportedArtifact* material = FindArtifact(*occlusion, AssetType::Material);
			REQUIRE(material != nullptr);
			Result<AssetRef<MaterialData>> loaded = LoadCookedMaterial(material->Cooked, fixture.GetRegistry());
			REQUIRE(loaded.has_value());
			CHECK_FALSE((*loaded)->OcclusionMap.IsValid());

			Result<ImportResult> colors = ImportGltf(fixture, "Assets/Models/VertexColors.gltf", MakeGltfMetadata(AssetHandle(0xf2)));
			REQUIRE_MESSAGE(colors.has_value(), colors.error().ToString());
			REQUIRE(colors->Diagnostics.size() == 1);
			CHECK(colors->Diagnostics.front().Code == AssetVertexColorsIgnoredCode);
		}

		TEST_CASE("GltfImporter: an image with its own Texture meta is referenced, not duplicated" * doctest::skip(true))
		{
			Test::AssetTestFixture fixture;
			CopyGltfFixtures(fixture);
			const AssetHandle standalone(0x5a5a000000000001ull);
			const std::vector<ImportAssetLookupEntry> assets = {
				{ .SourcePath = fixture.ProjectPath("Assets/Models/Textures/Shared.png"), .Handle = standalone, .Kind = AssetMetaKind::Asset, .Type = AssetType::Texture, .Owner = AssetHandle() },
			};
			Result<ImportResult> imported = ImportGltf(fixture, "Assets/Models/StandaloneTexture.gltf", MakeGltfMetadata(AssetHandle(0x51)), assets);
			REQUIRE_MESSAGE(imported.has_value(), imported.error().ToString());
			// No texture sub-asset: the material references the standalone texture, which becomes a dependency.
			CHECK(FindArtifact(*imported, AssetType::Texture) == nullptr);
			CHECK(std::ranges::find(imported->Dependencies, standalone) != imported->Dependencies.end());
			const ImportedArtifact* material = FindArtifact(*imported, AssetType::Material);
			REQUIRE(material != nullptr);
			Result<AssetRef<MaterialData>> loaded = LoadCookedMaterial(material->Cooked, fixture.GetRegistry());
			REQUIRE(loaded.has_value());
			CHECK((*loaded)->BaseColorMap.GetHandle() == standalone);

			// Without the standalone meta the same image becomes a texture sub-asset.
			Result<ImportResult> embedded = ImportGltf(fixture, "Assets/Models/StandaloneTexture.gltf", MakeGltfMetadata(AssetHandle(0x52)));
			REQUIRE(embedded.has_value());
			CHECK(FindArtifact(*embedded, AssetType::Texture) != nullptr);
		}

		TEST_CASE("GltfImporter: generated tangents agree with the file's tangents" * doctest::skip(true))
		{
			Test::AssetTestFixture fixture;
			CopyGltfFixtures(fixture);
			Result<ImportResult> withTangents = ImportGltf(fixture, "Assets/Models/NormalMapped.gltf", MakeGltfMetadata(AssetHandle(0x61)));
			Result<ImportResult> generated = ImportGltf(fixture, "Assets/Models/NormalMappedNoTangents.gltf", MakeGltfMetadata(AssetHandle(0x62)));
			REQUIRE(withTangents.has_value());
			REQUIRE(generated.has_value());
			// The fixtures share their geometry; the generator writes MikkTSpace tangents into NormalMapped.gltf.
			Result<AssetRef<MeshData>> fileMesh = LoadCookedMesh(FindArtifact(*withTangents, AssetType::Mesh)->Cooked);
			Result<AssetRef<MeshData>> generatedMesh = LoadCookedMesh(FindArtifact(*generated, AssetType::Mesh)->Cooked);
			REQUIRE(fileMesh.has_value());
			REQUIRE(generatedMesh.has_value());
			REQUIRE((*fileMesh)->Vertices.size() == (*generatedMesh)->Vertices.size());
			for (size_t index = 0; index < (*fileMesh)->Vertices.size(); ++index)
			{
				const glm::vec4 expected = (*fileMesh)->Vertices[index].Tangent;
				const glm::vec4 actual = (*generatedMesh)->Vertices[index].Tangent;
				CHECK(glm::dot(glm::vec3(expected), glm::vec3(actual)) == doctest::Approx(1.0f).epsilon(1e-3));
				CHECK(expected.w == actual.w);
			}
			CHECK(generated->Diagnostics.empty());
		}

		TEST_CASE("GltfImporter: ListExternalUris returns the dependency closure in glTF order" * doctest::skip(true))
		{
			Test::AssetTestFixture fixture;
			CopyGltfFixtures(fixture);
			Result<std::vector<std::string>> uris = GltfImporter::ListExternalUris(fixture.ReadProjectFile("Assets/Models/Textured.gltf"));
			REQUIRE_MESSAGE(uris.has_value(), uris.error().ToString());
			CHECK(*uris == std::vector<std::string>{ "Textured.bin", "Textures/Checker.png" });
			Result<std::vector<std::string>> embedded = GltfImporter::ListExternalUris(fixture.ReadProjectFile("Assets/Models/DataUri.gltf"));
			REQUIRE(embedded.has_value());
			CHECK(embedded->empty());

			// Decoded paths: exactly what Import reads and asset.import copies.
			Result<std::vector<std::string>> encoded = GltfImporter::ListExternalUris(fixture.ReadProjectFile("Assets/Models/EncodedUri.gltf"));
			REQUIRE_MESSAGE(encoded.has_value(), encoded.error().ToString());
			CHECK(*encoded == std::vector<std::string>{ "Encoded Data/Box.bin" });
			Result<ImportResult> imported = ImportGltf(fixture, "Assets/Models/EncodedUri.gltf", MakeGltfMetadata(AssetHandle(0x71)));
			REQUIRE_MESSAGE(imported.has_value(), imported.error().ToString());

			// ListDependencyFiles resolves them against the source's directory, sorted.
			Result<std::vector<VfsPath>> files = GltfImporter().ListDependencyFiles(fixture.ReadProjectFile("Assets/Models/Textured.gltf"),
				fixture.ProjectPath("Assets/Models/Textured.gltf"));
			REQUIRE_MESSAGE(files.has_value(), files.error().ToString());
			CHECK(*files == std::vector<VfsPath>{ fixture.ProjectPath("Assets/Models/Textured.bin"), fixture.ProjectPath("Assets/Models/Textures/Checker.png") });
		}

		TEST_CASE("GltfImporter: Scale is baked into the meshes and node translations, not the root transform" * doctest::skip(true))
		{
			Test::AssetTestFixture fixture;
			CopyGltfFixtures(fixture);
			Result<ImportResult> unit = ImportGltf(fixture, "Assets/Models/Box.gltf", MakeGltfMetadata(AssetHandle(0x81)));
			AssetMetadata scaledMetadata = MakeGltfMetadata(AssetHandle(0x81));
			Json settings = MakeDefaultSettings();
			settings["Scale"] = 0.5;
			scaledMetadata.Settings = VariantValue(std::move(settings));
			Result<ImportResult> scaled = ImportGltf(fixture, "Assets/Models/Box.gltf", scaledMetadata);
			REQUIRE_MESSAGE(unit.has_value(), unit.error().ToString());
			REQUIRE_MESSAGE(scaled.has_value(), scaled.error().ToString());

			Result<AssetRef<MeshData>> unitMesh = LoadCookedMesh(FindArtifact(*unit, AssetType::Mesh)->Cooked);
			Result<AssetRef<MeshData>> scaledMesh = LoadCookedMesh(FindArtifact(*scaled, AssetType::Mesh)->Cooked);
			REQUIRE(unitMesh.has_value());
			REQUIRE(scaledMesh.has_value());
			REQUIRE((*unitMesh)->Vertices.size() == (*scaledMesh)->Vertices.size());
			for (size_t index = 0; index < (*unitMesh)->Vertices.size(); ++index)
			{
				CHECK((*scaledMesh)->Vertices[index].Position == (*unitMesh)->Vertices[index].Position * 0.5f);
				CHECK((*scaledMesh)->Vertices[index].Normal == (*unitMesh)->Vertices[index].Normal);
			}
			CHECK((*scaledMesh)->Bounds.Min == (*unitMesh)->Bounds.Min * 0.5f);
			CHECK((*scaledMesh)->Bounds.Max == (*unitMesh)->Bounds.Max * 0.5f);

			// The prefab root keeps an identity Transform: every instance overrides the root's Transform implicitly (§5.5).
			Result<AssetRef<PrefabData>> prefab = LoadCookedPrefab(scaled->Artifacts.front().Cooked);
			REQUIRE(prefab.has_value());
			const Json& document = *(*prefab)->Document;
			const Json::json_pointer rootScale("/Entities/0/Components/Transform/Scale");
			REQUIRE(document.contains(rootScale));
			CHECK(document[rootScale] == Json::array({ 1, 1, 1 }));
		}
	}

}
