"""Scripts/Build.py's decision to copy the app-local CRT (Docs/Architecture.md §2.3; Docs/Decisions/0012-m7-decisions.md
decisions 14 and 22): every build that builds the Runtime, directly or as a dependency, copies it next to the Runtime,
where project.export takes it from; a build that does not build the Runtime copies nothing.

The solution is a small .slnx written into a temporary directory with the shape premake writes (the Tests project
depends on Runtime through a BuildDependency, Editor links EditorCore through a ProjectReference), so the test runs on
every system and needs no generated workspace.
"""

from __future__ import annotations

import sys
import tempfile
import unittest
from pathlib import Path

from harness import REPOSITORY_ROOT

sys.path.insert(0, str(REPOSITORY_ROOT / "Scripts"))

import Build  # noqa: E402  (Scripts/ is on sys.path above; Build imports its Lib package from there)
from Lib import workspace  # noqa: E402

SOLUTION = """<Solution Description="Visual Studio slnx file generated by Premake" Version="1.4">
  <Configurations>
    <BuildType Name="Debug" />
    <BuildType Name="Dist" />
    <Platform Name="x64" />
  </Configurations>
  <Project Path="Runtime\\Runtime.vcxproj" />
  <Project Path="Tests\\Tests.vcxproj">
    <Build Solution="Debug|x64" Project="true" />
    <Build Project="false" />
    <BuildDependency Project="Runtime\\Runtime.vcxproj" />
  </Project>
  <Project Path="Editor\\Editor.vcxproj">
    <Build Solution="Debug|x64" Project="true" />
    <Build Project="false" />
  </Project>
  <Folder Name="/Engine/">
    <Project Path="Engine\\Engine.vcxproj" />
    <Project Path="EditorCore\\EditorCore.vcxproj">
      <Build Solution="Debug|x64" Project="true" />
      <Build Project="false" />
    </Project>
  </Folder>
</Solution>
"""

# Each project file with the ProjectReference items of premake's links.
PROJECT_REFERENCES = {
    "Runtime": ["..\\Engine\\Engine.vcxproj"],
    "Tests": ["..\\EditorCore\\EditorCore.vcxproj", "..\\Engine\\Engine.vcxproj"],
    "Editor": ["..\\EditorCore\\EditorCore.vcxproj"],
    "Engine": [],
    "EditorCore": ["..\\Engine\\Engine.vcxproj"],
}


class BuildScriptTests(unittest.TestCase):
    def setUp(self) -> None:
        temporary = tempfile.TemporaryDirectory(prefix="EngineBuildScript")
        self.addCleanup(temporary.cleanup)
        root = Path(temporary.name)
        (root / "Workspace.slnx").write_text(SOLUTION, encoding="utf-8")
        for project, references in PROJECT_REFERENCES.items():
            items = "".join(f'    <ProjectReference Include="{reference}" />\n' for reference in references)
            text = (f'<Project DefaultTargets="Build">\n  <PropertyGroup>\n    <ConfigurationType>Application'
                    f'</ConfigurationType>\n  </PropertyGroup>\n  <ItemGroup>\n{items}  </ItemGroup>\n</Project>\n')
            (root / project).mkdir()
            (root / project / f"{project}.vcxproj").write_text(text, encoding="utf-8")
        self.solution = workspace.read_solution(root / "Workspace.slnx")

    def test_dependencies_come_from_build_dependencies_and_project_references(self) -> None:
        self.assertEqual(self.solution.dependencies["Tests"], {"Runtime", "EditorCore", "Engine"})
        self.assertEqual(self.solution.dependencies["Editor"], {"EditorCore"})
        self.assertEqual(self.solution.builds_with("Tests"), {"Tests", "Runtime", "EditorCore", "Engine"})
        self.assertEqual(self.solution.builds_with("Editor"), {"Editor", "EditorCore", "Engine"})

    def test_builds_that_build_the_runtime_copy_the_crt(self) -> None:
        # The whole configuration, the Runtime itself and Tests, which depends on it.
        self.assertTrue(Build.builds_runtime(self.solution, "Debug", None))
        self.assertTrue(Build.builds_runtime(self.solution, "Debug", "Runtime"))
        self.assertTrue(Build.builds_runtime(self.solution, "Debug", "Tests"))
        self.assertTrue(Build.builds_runtime(self.solution, "Dist", None))

    def test_builds_without_the_runtime_copy_nothing(self) -> None:
        self.assertFalse(Build.builds_runtime(self.solution, "Debug", "Editor"))
        self.assertFalse(Build.builds_runtime(self.solution, "Debug", "EditorCore"))
        self.assertFalse(Build.builds_runtime(self.solution, "Debug", "Engine"))


if __name__ == "__main__":
    unittest.main()
