#pragma once

#include "Engine/Core/Base.h"
#include "Engine/Core/Result.h"

#include <cstdint>
#include <filesystem>
#include <optional>
#include <string>
#include <string_view>
#include <vector>

// The exporter, v0 (Architecture §7.6, §14.1, §14.2; Roadmap M7): turns the open project into a standalone game folder
// that the Runtime executable runs. Used by project.export (EditorCore/Automation/ExportMethods.h); `Editor --export`,
// Scripts/Export.py, testing exports, resource patching and the notices file arrive with M15
// (Docs/Decisions/0012-m7-decisions.md decision 14).
//
// The package (§14.1), in OutputDirectory:
//   <Name>(.exe)                 the target configuration's Runtime executable, renamed after the project's Name
//   vcruntime140.dll vcruntime140_1.dll msvcp140.dll   Windows: the app-local CRT from bin/<OutputDir>/Runtime/Redist
//                                (copied there by Scripts/Build.py, §2.3)
//   Game.json                    the manifest (Engine/Project/GameManifest.h): Name, EngineVersion, StartScene, the paks
//                                with their XXH64, Window, Simulation, Testing false
//   Data/Engine.pak              the target configuration's shaders (every .spv and .refl.json file of
//                                bin/<OutputDir>/Shaders as plain files under "Shaders/", PakFormat.h) and the File
//                                built-ins of Resources/EngineAssets.json cooked from the engine cooked cache (the Default
//                                font); no environments (M8 bakes them; the Studio and Sky entries are left out with a
//                                warning). Metadata {"Configuration": "<Debug|Release|Dist>", "EngineVersion": "..."}.
//                                Procedural built-ins are generated by the Runtime's asset manager and are not in the pak.
//   Data/Game.pak                every registered asset under Assets/ (main assets and sub-assets) except the
//                                Export.Exclude globs, cooked through the editor's asset manager (Library/Cache, §7.5).
//                                Metadata {"Project": <the canonical ProjectSettings document>} (§14.1: the project settings
//                                ride in the TOC).
// Paks are written with PakWriter, so equal inputs give byte-identical paks (§7.6, "test_export_is_deterministic"); the
// manifest is written canonically (JsonWriter), so two exports of an unchanged project are identical file for file.
//
// The steps (§14.2), each failing the export with a located error and removing the partial output. Everything is built in
// a staging directory beside OutputDirectory (on the same volume) and reaches OutputDirectory only in step 7, so a failed or
// cancelled export leaves an earlier export there untouched:
//   1. Validate: a project is open; StartScene is set and is a registered scene; every Export.BuildScenes entry and the
//      start scene load strictly (SceneSerializer, LoadOptions Strict); the asset manager has no error diagnostic
//      (EditorAssetManager::HasErrorDiagnostics, §7.2); every asset handle a build scene references resolves; Name is a
//      valid file name. Scripts and replays join in M13/M15.
//   2. Cook every included asset (EditorAssetManager, incrementally from Library/Cache), on jobs.
//   3. Write Engine.pak and Game.pak atomically into the staging directory, then reopen both (PakReader) and verify every
//      hash.
//   4. Copy the Runtime executable of the target configuration, renamed, and on Windows its Redist/*.dll. A missing binary
//      is NotFound naming "python Scripts/Build.py --config <Config> --project Runtime"; the editor never builds.
//   5. Write Game.json: the staged package is complete.
//   6. Optionally run the smoke test (§14.2 step 7) on the staged package: its executable, with Game.json and the paks next
//      to it, with --headless --frames <SmokeTestFrames> --expect-no-errors and, per configuration:
//        - Debug and Release: --user-data-dir <a temporary directory beside the staging directory, never inside the
//          package>, so the run never writes the real profile; and --renderer none when the exporting editor has no
//          graphics device (EngineContext::GetGraphicsDevice: started with --renderer none, or no Vulkan device).
//        - Dist, which honours only §13.9's options: nothing more, so the run writes its log under <UserData>/<Name>/ as the
//          shipped game does. Without a graphics device in the exporting editor it cannot run (a Dist Runtime has no
//          --renderer none and exits 3 without a device): the test is not run, SmokeTestRan stays false and a warning
//          says why.
//      A non-zero exit code fails the export, naming the code and the end of its output.
//   7. Move the staging directory into OutputDirectory, replacing an earlier export there.
//   8. Return the report.
//
// Main thread only (the asset manager and the open scene are main-thread state, §4.11); the cooking and the smoke test's
// process run in the background, and Poll advances the export once per frame, so the editor stays responsive (§13.2
// "Pending operations"). Not copyable.

namespace Engine {

	class EditorContext;

	// The build configuration an export targets (§2.2): registry enum "ExportConfiguration".
	enum class ExportConfiguration : uint8_t
	{
		Debug,
		Release,
		Dist
	};

	// Where an export runs: the steps of the file comment, in order.
	enum class ExportPhase : uint8_t
	{
		Validate,
		Cook,
		WritePaks,
		CopyRuntime,
		WriteManifest,
		SmokeTest,
		MoveToOutput,
		Done
	};

	struct ExportSpecification
	{
		ExportConfiguration Configuration = ExportConfiguration::Release;
		// The project-relative output directory, which must lie under "Build/" (§13.2: project.export writes only under
		// <Project>/Build/); empty: GetDefaultOutputDirectory. Ignored when ExportRoot is set.
		std::string OutputDirectory{};
		// `Editor --export-root <dir>` (M15): an absolute directory the export goes into instead of the project's Build/;
		// empty: under the project.
		std::filesystem::path ExportRoot{};
		// The repository's bin directory, where bin/<Config>-<system>-<arch>/Runtime and .../Shaders of the target
		// configuration are (§14.2 step 4). The editor passes <repo>/bin (ENGINE_REPO_ROOT); tests pass the same. Required.
		std::filesystem::path BinaryRoot{};
		// Run step 6's smoke test.
		bool SmokeTest = false;
		// The smoke test's --frames (§14.2: 300).
		uint32_t SmokeTestFrames = 300;
	};

	// One file of the package.
	struct ExportedFile
	{
		std::string Path{}; // relative to the output directory, forward slashes
		uint64_t Size = 0;
		uint64_t Hash = 0; // XXH64 (seed 0) of the bytes
	};

	// What an export produced (§14.2 step 8).
	struct ExportReport
	{
		std::filesystem::path OutputDirectory{};
		std::filesystem::path Executable{};
		ExportConfiguration Configuration = ExportConfiguration::Release;
		std::vector<ExportedFile> Files{}; // sorted by Path
		uint32_t GameAssetCount = 0;       // cooked entries of Game.pak
		uint32_t EngineEntryCount = 0;     // entries of Engine.pak (shader files and built-ins)
		std::vector<std::string> Warnings{};
		// Whether step 6 ran the exported executable: false without SmokeTest, and for a Dist export from an editor without
		// a graphics device (with a warning).
		bool SmokeTestRan = false;
		int SmokeTestExitCode = 0;
		double Seconds = 0.0; // wall-clock duration, for the report only
	};

	class Exporter
	{
	public:
		// Restricts construction to Start; CreateScope still reaches the constructor.
		class ConstructionKey
		{
			ConstructionKey() = default;
			friend class Exporter;
		};

		// Use Start.
		explicit Exporter(ConstructionKey key);
		// Cancels a running export (as Cancel).
		~Exporter();

		Exporter(const Exporter&) = delete;
		Exporter& operator=(const Exporter&) = delete;

		// Starts exporting `editor`'s open project (a documented back-reference that outlives the exporter). Checks the
		// specification at once: InvalidState without a project or for a read-only project; InvalidArgument for an output
		// directory outside "Build/", an empty BinaryRoot, a ExportRoot that is not absolute, or SmokeTestFrames of 0. The
		// steps run in Poll.
		[[nodiscard]] static Result<Scope<Exporter>> Start(EditorContext& editor, const ExportSpecification& specification);

		// Advances the export (see the file comment); nullopt while it runs, then the report or the error of the step that
		// failed (with the context "while exporting <step>"). Never called again after it returned a value.
		[[nodiscard]] std::optional<Result<ExportReport>> Poll();

		// Stops the export: terminates a running smoke test, waits for cooking jobs, and removes the staging directory and
		// the smoke test's user-data directory; an earlier export in OutputDirectory stays untouched (the move is the last
		// step). Idempotent.
		void Cancel();

		[[nodiscard]] ExportPhase GetPhase() const;

		// "Build/<Platform>-<Config>/<Name>" (§14.1), with GetPlatformName and ExportConfigurationToString.
		[[nodiscard]] static std::string GetDefaultOutputDirectory(std::string_view projectName, ExportConfiguration configuration);
		// "Windows", "Linux" or "macOS": the host, which is the only platform an export targets (§1.2: no cross-OS export).
		[[nodiscard]] static std::string_view GetPlatformName();
		// The directory of a configuration's build outputs under BinaryRoot: "<Config>-<system>-<arch>" as premake names it
		// (premake5.lua OutputDir: "Release-windows-x86_64", "Dist-linux-x86_64", "Debug-macosx-AARCH64").
		[[nodiscard]] static std::string GetBuildOutputDirectoryName(ExportConfiguration configuration);
	private:
		// The editor, the specification, the phase, the staging directory, the cooking jobs, the smoke test's process and the
		// report being built (Exporter.cpp).
		struct State;
	private:
		Scope<State> m_State;
	};

	// "Debug", "Release" or "Dist".
	[[nodiscard]] std::string_view ExportConfigurationToString(ExportConfiguration configuration);
	// "Validate", "Cook", "WritePaks", "CopyRuntime", "WriteManifest", "SmokeTest", "MoveToOutput" or "Done".
	[[nodiscard]] std::string_view ExportPhaseToString(ExportPhase phase);

}
