#include "TestsPCH.h"

#include "Engine/Asset/BuiltinMeshes.h"

#include "Engine/Core/Hash.h"

#include <array>
#include <cmath>
#include <format>
#include <string>

namespace Engine {

	namespace {

		constexpr std::array<BuiltinMesh, 7> Meshes = { BuiltinMesh::Cube, BuiltinMesh::Sphere, BuiltinMesh::Plane, BuiltinMesh::Quad,
			BuiltinMesh::Cylinder, BuiltinMesh::Capsule, BuiltinMesh::Cone };

	}

	TEST_SUITE("Asset")
	{
		TEST_CASE("BuiltinMeshes: each mesh is named after its engine path and other values are Unknown")
		{
			CHECK(BuiltinMeshToString(BuiltinMesh::Cube) == "Cube");
			CHECK(BuiltinMeshToString(BuiltinMesh::Capsule) == "Capsule");
			CHECK(BuiltinMeshToString(static_cast<BuiltinMesh>(99)) == "Unknown");
		}

		TEST_CASE("BuiltinMeshes: generation is deterministic")
		{
			for (const BuiltinMesh mesh : Meshes)
			{
				CAPTURE(std::string(BuiltinMeshToString(mesh)));
				CHECK(SerializeMeshPayload(GenerateBuiltinMesh(mesh)) == SerializeMeshPayload(GenerateBuiltinMesh(mesh)));
			}
		}

		TEST_CASE("BuiltinMeshes: the generated bytes match the hashes recorded in every configuration")
		{
			// Recorded once; DetMath and IEEE-exact arithmetic make them hold in Debug and Release and on every platform
			// (Roadmap rule 1: a hash recorded in one configuration verifies in all of them).
			constexpr std::array<uint64_t, 7> RecordedHashes = { 0xac49cd809a3518a6ull, 0xd29228bb9c28f795ull, 0x258c21b35b8135e7ull,
				0xaf8f7a428e5e5875ull, 0x1b747fac05c16057ull, 0xb9e5b87b9944a2c6ull, 0xaba0e8c02c132207ull };
			for (size_t index = 0; index < Meshes.size(); ++index)
			{
				CAPTURE(std::string(BuiltinMeshToString(Meshes[index])));
				const uint64_t hash = XXH64(SerializeMeshPayload(GenerateBuiltinMesh(Meshes[index])));
				CAPTURE(std::format("{:016x}", hash));
				CHECK(hash == RecordedHashes[index]);
			}
		}

		TEST_CASE("BuiltinMeshes: every mesh is valid, unit size and outward-facing")
		{
			for (const BuiltinMesh shape : Meshes)
			{
				CAPTURE(std::string(BuiltinMeshToString(shape)));
				const MeshData mesh = GenerateBuiltinMesh(shape);
				REQUIRE(ValidateMeshData(mesh).has_value());
				REQUIRE(mesh.Submeshes.size() == 1);
				REQUIRE(mesh.Slots.size() == 1);
				CHECK(mesh.Slots.front().Name == "Default");
				CHECK_FALSE(mesh.Slots.front().DefaultMaterial.IsValid());
				// Centred on the origin, 1 m across in X (the capsule is 2 m tall, the plane and quad are flat).
				CHECK(mesh.Bounds.GetCenter().x == doctest::Approx(0.0f).epsilon(1e-6));
				CHECK(mesh.Bounds.GetSize().x == doctest::Approx(1.0f).epsilon(1e-6));
				// Outward: every triangle's geometric normal agrees with its first vertex's normal.
				for (size_t index = 0; index < mesh.Indices.size(); index += 3)
				{
					const MeshVertex& a = mesh.Vertices[mesh.Indices[index]];
					const MeshVertex& b = mesh.Vertices[mesh.Indices[index + 1]];
					const MeshVertex& c = mesh.Vertices[mesh.Indices[index + 2]];
					const glm::vec3 geometric = glm::cross(b.Position - a.Position, c.Position - a.Position);
					if (glm::dot(geometric, geometric) > 1e-12f)
						CHECK(glm::dot(geometric, a.Normal) > 0.0f);
				}
			}
			CHECK(GenerateBuiltinMesh(BuiltinMesh::Capsule).Bounds.GetSize().y == doctest::Approx(2.0f).epsilon(1e-6));
			CHECK(GenerateBuiltinMesh(BuiltinMesh::Plane).Bounds.GetSize().y == 0.0f);
			CHECK(GenerateBuiltinMesh(BuiltinMesh::Cube).Vertices.size() == 24);
		}

		TEST_CASE("BuiltinMeshes: every mesh has exact unit bounds and its documented tessellation")
		{
			const MeshData cube = GenerateBuiltinMesh(BuiltinMesh::Cube);
			CHECK(cube.Bounds.Min == glm::vec3(-0.5f));
			CHECK(cube.Bounds.Max == glm::vec3(0.5f));
			CHECK(cube.Indices.size() == 36);

			const MeshData sphere = GenerateBuiltinMesh(BuiltinMesh::Sphere);
			CHECK(sphere.Bounds.Min == glm::vec3(-0.5f));
			CHECK(sphere.Bounds.Max == glm::vec3(0.5f));
			// 32 segments x 16 rings: one triangle per segment at each pole, two per segment between the other rings.
			CHECK(sphere.Indices.size() == 3 * (2 * 32 + 2 * 32 * 14));
			for (const MeshVertex& vertex : sphere.Vertices)
				CHECK(glm::length(vertex.Position) == doctest::Approx(0.5f).epsilon(1e-6));

			const MeshData plane = GenerateBuiltinMesh(BuiltinMesh::Plane);
			CHECK(plane.Vertices.size() == 11 * 11);
			CHECK(plane.Indices.size() == 3 * 2 * 10 * 10);
			CHECK(plane.Bounds.Min == glm::vec3(-0.5f, 0.0f, -0.5f));
			CHECK(plane.Bounds.Max == glm::vec3(0.5f, 0.0f, 0.5f));

			const MeshData quad = GenerateBuiltinMesh(BuiltinMesh::Quad);
			CHECK(quad.Vertices.size() == 4);
			CHECK(quad.Bounds.Min == glm::vec3(-0.5f, -0.5f, 0.0f));
			CHECK(quad.Bounds.Max == glm::vec3(0.5f, 0.5f, 0.0f));

			const MeshData cylinder = GenerateBuiltinMesh(BuiltinMesh::Cylinder);
			CHECK(cylinder.Bounds.Min == glm::vec3(-0.5f));
			CHECK(cylinder.Bounds.Max == glm::vec3(0.5f));

			const MeshData capsule = GenerateBuiltinMesh(BuiltinMesh::Capsule);
			CHECK(capsule.Bounds.Min == glm::vec3(-0.5f, -1.0f, -0.5f));
			CHECK(capsule.Bounds.Max == glm::vec3(0.5f, 1.0f, 0.5f));

			const MeshData cone = GenerateBuiltinMesh(BuiltinMesh::Cone);
			CHECK(cone.Bounds.Min == glm::vec3(-0.5f));
			CHECK(cone.Bounds.Max == glm::vec3(0.5f));
		}

		TEST_CASE("BuiltinMeshes: tangents follow U and bitangents point to the top of the texture")
		{
			// glTF convention (MeshData.h): bitangent = cross(Normal, Tangent.xyz) * Tangent.w points to decreasing V (the top
			// of the texture), so an unmirrored mapping has sign +1. Each triangle's own UV gradient is compared with its vertices.
			for (const BuiltinMesh shape : Meshes)
			{
				CAPTURE(std::string(BuiltinMeshToString(shape)));
				const MeshData mesh = GenerateBuiltinMesh(shape);
				for (const MeshVertex& vertex : mesh.Vertices)
				{
					CHECK(vertex.Tangent.w == 1.0f);
					CHECK(std::fabs(glm::dot(vertex.Normal, glm::vec3(vertex.Tangent))) < 1e-5f);
					CHECK(vertex.TexCoord.x >= 0.0f);
					CHECK(vertex.TexCoord.x <= 1.0f);
					CHECK(vertex.TexCoord.y >= 0.0f);
					CHECK(vertex.TexCoord.y <= 1.0f);
				}
				for (size_t index = 0; index < mesh.Indices.size(); index += 3)
				{
					const MeshVertex& a = mesh.Vertices[mesh.Indices[index]];
					const MeshVertex& b = mesh.Vertices[mesh.Indices[index + 1]];
					const MeshVertex& c = mesh.Vertices[mesh.Indices[index + 2]];
					const glm::vec3 edge1 = b.Position - a.Position;
					const glm::vec3 edge2 = c.Position - a.Position;
					const glm::vec2 uv1 = b.TexCoord - a.TexCoord;
					const glm::vec2 uv2 = c.TexCoord - a.TexCoord;
					const float determinant = uv1.x * uv2.y - uv2.x * uv1.y;
					if (std::fabs(determinant) < 1e-9f)
						continue;
					// Counter-clockwise from outside with V growing downwards: the UV triangle winds clockwise.
					CHECK(determinant < 0.0f);
					const glm::vec3 alongU = (edge1 * uv2.y - edge2 * uv1.y) / determinant;
					const glm::vec3 alongV = (edge2 * uv1.x - edge1 * uv2.x) / determinant;
					for (const MeshVertex* vertex : { &a, &b, &c })
					{
						const glm::vec3 bitangent = glm::cross(vertex->Normal, glm::vec3(vertex->Tangent)) * vertex->Tangent.w;
						CHECK(glm::dot(alongU, glm::vec3(vertex->Tangent)) > 0.0f);
						CHECK(glm::dot(alongV, bitangent) < 0.0f);
					}
				}
			}
		}
	}

}
